// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `commands/display_zone_image.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:display_zone_image.SetDisplayZoneImage)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SetDisplayZoneImage {
    // message fields
    // @@protoc_insertion_point(field:display_zone_image.SetDisplayZoneImage.display_zone)
    pub display_zone: ::protobuf::EnumOrUnknown<super::display_zones::DisplayZone>,
    // @@protoc_insertion_point(field:display_zone_image.SetDisplayZoneImage.image_path)
    pub image_path: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:display_zone_image.SetDisplayZoneImage.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SetDisplayZoneImage {
    fn default() -> &'a SetDisplayZoneImage {
        <SetDisplayZoneImage as ::protobuf::Message>::default_instance()
    }
}

impl SetDisplayZoneImage {
    pub fn new() -> SetDisplayZoneImage {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "display_zone",
            |m: &SetDisplayZoneImage| { &m.display_zone },
            |m: &mut SetDisplayZoneImage| { &mut m.display_zone },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "image_path",
            |m: &SetDisplayZoneImage| { &m.image_path },
            |m: &mut SetDisplayZoneImage| { &mut m.image_path },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SetDisplayZoneImage>(
            "SetDisplayZoneImage",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SetDisplayZoneImage {
    const NAME: &'static str = "SetDisplayZoneImage";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.display_zone = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.image_path = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.display_zone != ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.display_zone.value());
        }
        if !self.image_path.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.image_path);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.display_zone != ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.display_zone))?;
        }
        if !self.image_path.is_empty() {
            os.write_string(2, &self.image_path)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SetDisplayZoneImage {
        SetDisplayZoneImage::new()
    }

    fn clear(&mut self) {
        self.display_zone = ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED);
        self.image_path.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SetDisplayZoneImage {
        static instance: SetDisplayZoneImage = SetDisplayZoneImage {
            display_zone: ::protobuf::EnumOrUnknown::from_i32(0),
            image_path: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SetDisplayZoneImage {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SetDisplayZoneImage").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SetDisplayZoneImage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetDisplayZoneImage {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:display_zone_image.ClearDisplayZoneImage)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ClearDisplayZoneImage {
    // message fields
    // @@protoc_insertion_point(field:display_zone_image.ClearDisplayZoneImage.display_zone)
    pub display_zone: ::protobuf::EnumOrUnknown<super::display_zones::DisplayZone>,
    // special fields
    // @@protoc_insertion_point(special_field:display_zone_image.ClearDisplayZoneImage.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ClearDisplayZoneImage {
    fn default() -> &'a ClearDisplayZoneImage {
        <ClearDisplayZoneImage as ::protobuf::Message>::default_instance()
    }
}

impl ClearDisplayZoneImage {
    pub fn new() -> ClearDisplayZoneImage {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "display_zone",
            |m: &ClearDisplayZoneImage| { &m.display_zone },
            |m: &mut ClearDisplayZoneImage| { &mut m.display_zone },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ClearDisplayZoneImage>(
            "ClearDisplayZoneImage",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ClearDisplayZoneImage {
    const NAME: &'static str = "ClearDisplayZoneImage";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.display_zone = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.display_zone != ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.display_zone.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.display_zone != ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.display_zone))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ClearDisplayZoneImage {
        ClearDisplayZoneImage::new()
    }

    fn clear(&mut self) {
        self.display_zone = ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ClearDisplayZoneImage {
        static instance: ClearDisplayZoneImage = ClearDisplayZoneImage {
            display_zone: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ClearDisplayZoneImage {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ClearDisplayZoneImage").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ClearDisplayZoneImage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClearDisplayZoneImage {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:display_zone_image.ClearAllDisplayZoneImages)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ClearAllDisplayZoneImages {
    // message fields
    // @@protoc_insertion_point(field:display_zone_image.ClearAllDisplayZoneImages.unpersist_images)
    pub unpersist_images: bool,
    // special fields
    // @@protoc_insertion_point(special_field:display_zone_image.ClearAllDisplayZoneImages.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ClearAllDisplayZoneImages {
    fn default() -> &'a ClearAllDisplayZoneImages {
        <ClearAllDisplayZoneImages as ::protobuf::Message>::default_instance()
    }
}

impl ClearAllDisplayZoneImages {
    pub fn new() -> ClearAllDisplayZoneImages {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "unpersist_images",
            |m: &ClearAllDisplayZoneImages| { &m.unpersist_images },
            |m: &mut ClearAllDisplayZoneImages| { &mut m.unpersist_images },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ClearAllDisplayZoneImages>(
            "ClearAllDisplayZoneImages",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ClearAllDisplayZoneImages {
    const NAME: &'static str = "ClearAllDisplayZoneImages";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.unpersist_images = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.unpersist_images != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.unpersist_images != false {
            os.write_bool(1, self.unpersist_images)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ClearAllDisplayZoneImages {
        ClearAllDisplayZoneImages::new()
    }

    fn clear(&mut self) {
        self.unpersist_images = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ClearAllDisplayZoneImages {
        static instance: ClearAllDisplayZoneImages = ClearAllDisplayZoneImages {
            unpersist_images: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ClearAllDisplayZoneImages {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ClearAllDisplayZoneImages").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ClearAllDisplayZoneImages {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClearAllDisplayZoneImages {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n!commands/display_zone_image.proto\x12\x12display_zone_image\x1a#comma\
    nds/common/display_zones.proto\"e\n\x13SetDisplayZoneImage\x12/\n\x0cdis\
    play_zone\x18\x01\x20\x01(\x0e2\x0c.DisplayZoneR\x0bdisplayZone\x12\x1d\
    \n\nimage_path\x18\x02\x20\x01(\tR\timagePath\"H\n\x15ClearDisplayZoneIm\
    age\x12/\n\x0cdisplay_zone\x18\x01\x20\x01(\x0e2\x0c.DisplayZoneR\x0bdis\
    playZone\"F\n\x19ClearAllDisplayZoneImages\x12)\n\x10unpersist_images\
    \x18\x01\x20\x01(\x08R\x0funpersistImagesb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::display_zones::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(SetDisplayZoneImage::generated_message_descriptor_data());
            messages.push(ClearDisplayZoneImage::generated_message_descriptor_data());
            messages.push(ClearAllDisplayZoneImages::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
