// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `commands/common/display_zones.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:DisplayZone)
pub enum DisplayZone {
    // @@protoc_insertion_point(enum_value:DisplayZone.DISPLAY_ZONE_UNSPECIFIED)
    DISPLAY_ZONE_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_1)
    BUTTON_1 = 1,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_2)
    BUTTON_2 = 2,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_3)
    BUTTON_3 = 3,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_4)
    BUTTON_4 = 4,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_5)
    BUTTON_5 = 5,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_6)
    BUTTON_6 = 6,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_7)
    BUTTON_7 = 7,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_8)
    BUTTON_8 = 8,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_9)
    BUTTON_9 = 9,
    // @@protoc_insertion_point(enum_value:DisplayZone.BUTTON_10)
    BUTTON_10 = 10,
    // @@protoc_insertion_point(enum_value:DisplayZone.TOUCHSCREEN_ZONE_1)
    TOUCHSCREEN_ZONE_1 = 11,
    // @@protoc_insertion_point(enum_value:DisplayZone.TOUCHSCREEN_ZONE_2)
    TOUCHSCREEN_ZONE_2 = 12,
    // @@protoc_insertion_point(enum_value:DisplayZone.TOUCHSCREEN_ZONE_3)
    TOUCHSCREEN_ZONE_3 = 13,
    // @@protoc_insertion_point(enum_value:DisplayZone.TOUCHSCREEN_ZONE_4)
    TOUCHSCREEN_ZONE_4 = 14,
}

impl ::protobuf::Enum for DisplayZone {
    const NAME: &'static str = "DisplayZone";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<DisplayZone> {
        match value {
            0 => ::std::option::Option::Some(DisplayZone::DISPLAY_ZONE_UNSPECIFIED),
            1 => ::std::option::Option::Some(DisplayZone::BUTTON_1),
            2 => ::std::option::Option::Some(DisplayZone::BUTTON_2),
            3 => ::std::option::Option::Some(DisplayZone::BUTTON_3),
            4 => ::std::option::Option::Some(DisplayZone::BUTTON_4),
            5 => ::std::option::Option::Some(DisplayZone::BUTTON_5),
            6 => ::std::option::Option::Some(DisplayZone::BUTTON_6),
            7 => ::std::option::Option::Some(DisplayZone::BUTTON_7),
            8 => ::std::option::Option::Some(DisplayZone::BUTTON_8),
            9 => ::std::option::Option::Some(DisplayZone::BUTTON_9),
            10 => ::std::option::Option::Some(DisplayZone::BUTTON_10),
            11 => ::std::option::Option::Some(DisplayZone::TOUCHSCREEN_ZONE_1),
            12 => ::std::option::Option::Some(DisplayZone::TOUCHSCREEN_ZONE_2),
            13 => ::std::option::Option::Some(DisplayZone::TOUCHSCREEN_ZONE_3),
            14 => ::std::option::Option::Some(DisplayZone::TOUCHSCREEN_ZONE_4),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<DisplayZone> {
        match str {
            "DISPLAY_ZONE_UNSPECIFIED" => ::std::option::Option::Some(DisplayZone::DISPLAY_ZONE_UNSPECIFIED),
            "BUTTON_1" => ::std::option::Option::Some(DisplayZone::BUTTON_1),
            "BUTTON_2" => ::std::option::Option::Some(DisplayZone::BUTTON_2),
            "BUTTON_3" => ::std::option::Option::Some(DisplayZone::BUTTON_3),
            "BUTTON_4" => ::std::option::Option::Some(DisplayZone::BUTTON_4),
            "BUTTON_5" => ::std::option::Option::Some(DisplayZone::BUTTON_5),
            "BUTTON_6" => ::std::option::Option::Some(DisplayZone::BUTTON_6),
            "BUTTON_7" => ::std::option::Option::Some(DisplayZone::BUTTON_7),
            "BUTTON_8" => ::std::option::Option::Some(DisplayZone::BUTTON_8),
            "BUTTON_9" => ::std::option::Option::Some(DisplayZone::BUTTON_9),
            "BUTTON_10" => ::std::option::Option::Some(DisplayZone::BUTTON_10),
            "TOUCHSCREEN_ZONE_1" => ::std::option::Option::Some(DisplayZone::TOUCHSCREEN_ZONE_1),
            "TOUCHSCREEN_ZONE_2" => ::std::option::Option::Some(DisplayZone::TOUCHSCREEN_ZONE_2),
            "TOUCHSCREEN_ZONE_3" => ::std::option::Option::Some(DisplayZone::TOUCHSCREEN_ZONE_3),
            "TOUCHSCREEN_ZONE_4" => ::std::option::Option::Some(DisplayZone::TOUCHSCREEN_ZONE_4),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [DisplayZone] = &[
        DisplayZone::DISPLAY_ZONE_UNSPECIFIED,
        DisplayZone::BUTTON_1,
        DisplayZone::BUTTON_2,
        DisplayZone::BUTTON_3,
        DisplayZone::BUTTON_4,
        DisplayZone::BUTTON_5,
        DisplayZone::BUTTON_6,
        DisplayZone::BUTTON_7,
        DisplayZone::BUTTON_8,
        DisplayZone::BUTTON_9,
        DisplayZone::BUTTON_10,
        DisplayZone::TOUCHSCREEN_ZONE_1,
        DisplayZone::TOUCHSCREEN_ZONE_2,
        DisplayZone::TOUCHSCREEN_ZONE_3,
        DisplayZone::TOUCHSCREEN_ZONE_4,
    ];
}

impl ::protobuf::EnumFull for DisplayZone {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("DisplayZone").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for DisplayZone {
    fn default() -> Self {
        DisplayZone::DISPLAY_ZONE_UNSPECIFIED
    }
}

impl DisplayZone {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<DisplayZone>("DisplayZone")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n#commands/common/display_zones.proto*\x98\x02\n\x0bDisplayZone\x12\x1c\
    \n\x18DISPLAY_ZONE_UNSPECIFIED\x10\0\x12\x0c\n\x08BUTTON_1\x10\x01\x12\
    \x0c\n\x08BUTTON_2\x10\x02\x12\x0c\n\x08BUTTON_3\x10\x03\x12\x0c\n\x08BU\
    TTON_4\x10\x04\x12\x0c\n\x08BUTTON_5\x10\x05\x12\x0c\n\x08BUTTON_6\x10\
    \x06\x12\x0c\n\x08BUTTON_7\x10\x07\x12\x0c\n\x08BUTTON_8\x10\x08\x12\x0c\
    \n\x08BUTTON_9\x10\t\x12\r\n\tBUTTON_10\x10\n\x12\x16\n\x12TOUCHSCREEN_Z\
    ONE_1\x10\x0b\x12\x16\n\x12TOUCHSCREEN_ZONE_2\x10\x0c\x12\x16\n\x12TOUCH\
    SCREEN_ZONE_3\x10\r\x12\x16\n\x12TOUCHSCREEN_ZONE_4\x10\x0eb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(DisplayZone::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
