// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `commands/common/inputs.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:InputId)
pub enum InputId {
    // @@protoc_insertion_point(enum_value:InputId.INPUT_ACTION_UNSPECIFIED)
    INPUT_ACTION_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_1_PRESSED)
    BUTTON_1_PRESSED = 1,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_2_PRESSED)
    BUTTON_2_PRESSED = 2,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_3_PRESSED)
    BUTTON_3_PRESSED = 3,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_4_PRESSED)
    BUTTON_4_PRESSED = 4,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_5_PRESSED)
    BUTTON_5_PRESSED = 5,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_6_PRESSED)
    BUTTON_6_PRESSED = 6,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_7_PRESSED)
    BUTTON_7_PRESSED = 7,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_8_PRESSED)
    BUTTON_8_PRESSED = 8,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_9_PRESSED)
    BUTTON_9_PRESSED = 9,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_10_PRESSED)
    BUTTON_10_PRESSED = 10,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_1_RELEASED)
    BUTTON_1_RELEASED = 11,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_2_RELEASED)
    BUTTON_2_RELEASED = 12,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_3_RELEASED)
    BUTTON_3_RELEASED = 13,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_4_RELEASED)
    BUTTON_4_RELEASED = 14,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_5_RELEASED)
    BUTTON_5_RELEASED = 15,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_6_RELEASED)
    BUTTON_6_RELEASED = 16,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_7_RELEASED)
    BUTTON_7_RELEASED = 17,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_8_RELEASED)
    BUTTON_8_RELEASED = 18,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_9_RELEASED)
    BUTTON_9_RELEASED = 19,
    // @@protoc_insertion_point(enum_value:InputId.BUTTON_10_RELEASED)
    BUTTON_10_RELEASED = 20,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_1_CLOCKWISE)
    KNOB_1_CLOCKWISE = 21,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_2_CLOCKWISE)
    KNOB_2_CLOCKWISE = 22,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_3_CLOCKWISE)
    KNOB_3_CLOCKWISE = 23,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_4_CLOCKWISE)
    KNOB_4_CLOCKWISE = 24,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_1_COUNTER_CLOCKWISE)
    KNOB_1_COUNTER_CLOCKWISE = 25,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_2_COUNTER_CLOCKWISE)
    KNOB_2_COUNTER_CLOCKWISE = 26,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_3_COUNTER_CLOCKWISE)
    KNOB_3_COUNTER_CLOCKWISE = 27,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_4_COUNTER_CLOCKWISE)
    KNOB_4_COUNTER_CLOCKWISE = 28,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_1_PRESSED)
    KNOB_1_PRESSED = 29,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_2_PRESSED)
    KNOB_2_PRESSED = 30,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_3_PRESSED)
    KNOB_3_PRESSED = 31,
    // @@protoc_insertion_point(enum_value:InputId.KNOB_4_PRESSED)
    KNOB_4_PRESSED = 32,
    // @@protoc_insertion_point(enum_value:InputId.TOUCHSCREEN_ZONE_1_PRESSED)
    TOUCHSCREEN_ZONE_1_PRESSED = 33,
    // @@protoc_insertion_point(enum_value:InputId.TOUCHSCREEN_ZONE_2_PRESSED)
    TOUCHSCREEN_ZONE_2_PRESSED = 34,
    // @@protoc_insertion_point(enum_value:InputId.TOUCHSCREEN_ZONE_3_PRESSED)
    TOUCHSCREEN_ZONE_3_PRESSED = 35,
    // @@protoc_insertion_point(enum_value:InputId.TOUCHSCREEN_ZONE_4_PRESSED)
    TOUCHSCREEN_ZONE_4_PRESSED = 36,
    // @@protoc_insertion_point(enum_value:InputId.TOUCHSCREEN_SWIPED_LEFT)
    TOUCHSCREEN_SWIPED_LEFT = 37,
    // @@protoc_insertion_point(enum_value:InputId.TOUCHSCREEN_SWIPED_RIGHT)
    TOUCHSCREEN_SWIPED_RIGHT = 38,
}

impl ::protobuf::Enum for InputId {
    const NAME: &'static str = "InputId";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<InputId> {
        match value {
            0 => ::std::option::Option::Some(InputId::INPUT_ACTION_UNSPECIFIED),
            1 => ::std::option::Option::Some(InputId::BUTTON_1_PRESSED),
            2 => ::std::option::Option::Some(InputId::BUTTON_2_PRESSED),
            3 => ::std::option::Option::Some(InputId::BUTTON_3_PRESSED),
            4 => ::std::option::Option::Some(InputId::BUTTON_4_PRESSED),
            5 => ::std::option::Option::Some(InputId::BUTTON_5_PRESSED),
            6 => ::std::option::Option::Some(InputId::BUTTON_6_PRESSED),
            7 => ::std::option::Option::Some(InputId::BUTTON_7_PRESSED),
            8 => ::std::option::Option::Some(InputId::BUTTON_8_PRESSED),
            9 => ::std::option::Option::Some(InputId::BUTTON_9_PRESSED),
            10 => ::std::option::Option::Some(InputId::BUTTON_10_PRESSED),
            11 => ::std::option::Option::Some(InputId::BUTTON_1_RELEASED),
            12 => ::std::option::Option::Some(InputId::BUTTON_2_RELEASED),
            13 => ::std::option::Option::Some(InputId::BUTTON_3_RELEASED),
            14 => ::std::option::Option::Some(InputId::BUTTON_4_RELEASED),
            15 => ::std::option::Option::Some(InputId::BUTTON_5_RELEASED),
            16 => ::std::option::Option::Some(InputId::BUTTON_6_RELEASED),
            17 => ::std::option::Option::Some(InputId::BUTTON_7_RELEASED),
            18 => ::std::option::Option::Some(InputId::BUTTON_8_RELEASED),
            19 => ::std::option::Option::Some(InputId::BUTTON_9_RELEASED),
            20 => ::std::option::Option::Some(InputId::BUTTON_10_RELEASED),
            21 => ::std::option::Option::Some(InputId::KNOB_1_CLOCKWISE),
            22 => ::std::option::Option::Some(InputId::KNOB_2_CLOCKWISE),
            23 => ::std::option::Option::Some(InputId::KNOB_3_CLOCKWISE),
            24 => ::std::option::Option::Some(InputId::KNOB_4_CLOCKWISE),
            25 => ::std::option::Option::Some(InputId::KNOB_1_COUNTER_CLOCKWISE),
            26 => ::std::option::Option::Some(InputId::KNOB_2_COUNTER_CLOCKWISE),
            27 => ::std::option::Option::Some(InputId::KNOB_3_COUNTER_CLOCKWISE),
            28 => ::std::option::Option::Some(InputId::KNOB_4_COUNTER_CLOCKWISE),
            29 => ::std::option::Option::Some(InputId::KNOB_1_PRESSED),
            30 => ::std::option::Option::Some(InputId::KNOB_2_PRESSED),
            31 => ::std::option::Option::Some(InputId::KNOB_3_PRESSED),
            32 => ::std::option::Option::Some(InputId::KNOB_4_PRESSED),
            33 => ::std::option::Option::Some(InputId::TOUCHSCREEN_ZONE_1_PRESSED),
            34 => ::std::option::Option::Some(InputId::TOUCHSCREEN_ZONE_2_PRESSED),
            35 => ::std::option::Option::Some(InputId::TOUCHSCREEN_ZONE_3_PRESSED),
            36 => ::std::option::Option::Some(InputId::TOUCHSCREEN_ZONE_4_PRESSED),
            37 => ::std::option::Option::Some(InputId::TOUCHSCREEN_SWIPED_LEFT),
            38 => ::std::option::Option::Some(InputId::TOUCHSCREEN_SWIPED_RIGHT),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<InputId> {
        match str {
            "INPUT_ACTION_UNSPECIFIED" => ::std::option::Option::Some(InputId::INPUT_ACTION_UNSPECIFIED),
            "BUTTON_1_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_1_PRESSED),
            "BUTTON_2_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_2_PRESSED),
            "BUTTON_3_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_3_PRESSED),
            "BUTTON_4_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_4_PRESSED),
            "BUTTON_5_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_5_PRESSED),
            "BUTTON_6_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_6_PRESSED),
            "BUTTON_7_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_7_PRESSED),
            "BUTTON_8_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_8_PRESSED),
            "BUTTON_9_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_9_PRESSED),
            "BUTTON_10_PRESSED" => ::std::option::Option::Some(InputId::BUTTON_10_PRESSED),
            "BUTTON_1_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_1_RELEASED),
            "BUTTON_2_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_2_RELEASED),
            "BUTTON_3_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_3_RELEASED),
            "BUTTON_4_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_4_RELEASED),
            "BUTTON_5_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_5_RELEASED),
            "BUTTON_6_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_6_RELEASED),
            "BUTTON_7_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_7_RELEASED),
            "BUTTON_8_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_8_RELEASED),
            "BUTTON_9_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_9_RELEASED),
            "BUTTON_10_RELEASED" => ::std::option::Option::Some(InputId::BUTTON_10_RELEASED),
            "KNOB_1_CLOCKWISE" => ::std::option::Option::Some(InputId::KNOB_1_CLOCKWISE),
            "KNOB_2_CLOCKWISE" => ::std::option::Option::Some(InputId::KNOB_2_CLOCKWISE),
            "KNOB_3_CLOCKWISE" => ::std::option::Option::Some(InputId::KNOB_3_CLOCKWISE),
            "KNOB_4_CLOCKWISE" => ::std::option::Option::Some(InputId::KNOB_4_CLOCKWISE),
            "KNOB_1_COUNTER_CLOCKWISE" => ::std::option::Option::Some(InputId::KNOB_1_COUNTER_CLOCKWISE),
            "KNOB_2_COUNTER_CLOCKWISE" => ::std::option::Option::Some(InputId::KNOB_2_COUNTER_CLOCKWISE),
            "KNOB_3_COUNTER_CLOCKWISE" => ::std::option::Option::Some(InputId::KNOB_3_COUNTER_CLOCKWISE),
            "KNOB_4_COUNTER_CLOCKWISE" => ::std::option::Option::Some(InputId::KNOB_4_COUNTER_CLOCKWISE),
            "KNOB_1_PRESSED" => ::std::option::Option::Some(InputId::KNOB_1_PRESSED),
            "KNOB_2_PRESSED" => ::std::option::Option::Some(InputId::KNOB_2_PRESSED),
            "KNOB_3_PRESSED" => ::std::option::Option::Some(InputId::KNOB_3_PRESSED),
            "KNOB_4_PRESSED" => ::std::option::Option::Some(InputId::KNOB_4_PRESSED),
            "TOUCHSCREEN_ZONE_1_PRESSED" => ::std::option::Option::Some(InputId::TOUCHSCREEN_ZONE_1_PRESSED),
            "TOUCHSCREEN_ZONE_2_PRESSED" => ::std::option::Option::Some(InputId::TOUCHSCREEN_ZONE_2_PRESSED),
            "TOUCHSCREEN_ZONE_3_PRESSED" => ::std::option::Option::Some(InputId::TOUCHSCREEN_ZONE_3_PRESSED),
            "TOUCHSCREEN_ZONE_4_PRESSED" => ::std::option::Option::Some(InputId::TOUCHSCREEN_ZONE_4_PRESSED),
            "TOUCHSCREEN_SWIPED_LEFT" => ::std::option::Option::Some(InputId::TOUCHSCREEN_SWIPED_LEFT),
            "TOUCHSCREEN_SWIPED_RIGHT" => ::std::option::Option::Some(InputId::TOUCHSCREEN_SWIPED_RIGHT),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [InputId] = &[
        InputId::INPUT_ACTION_UNSPECIFIED,
        InputId::BUTTON_1_PRESSED,
        InputId::BUTTON_2_PRESSED,
        InputId::BUTTON_3_PRESSED,
        InputId::BUTTON_4_PRESSED,
        InputId::BUTTON_5_PRESSED,
        InputId::BUTTON_6_PRESSED,
        InputId::BUTTON_7_PRESSED,
        InputId::BUTTON_8_PRESSED,
        InputId::BUTTON_9_PRESSED,
        InputId::BUTTON_10_PRESSED,
        InputId::BUTTON_1_RELEASED,
        InputId::BUTTON_2_RELEASED,
        InputId::BUTTON_3_RELEASED,
        InputId::BUTTON_4_RELEASED,
        InputId::BUTTON_5_RELEASED,
        InputId::BUTTON_6_RELEASED,
        InputId::BUTTON_7_RELEASED,
        InputId::BUTTON_8_RELEASED,
        InputId::BUTTON_9_RELEASED,
        InputId::BUTTON_10_RELEASED,
        InputId::KNOB_1_CLOCKWISE,
        InputId::KNOB_2_CLOCKWISE,
        InputId::KNOB_3_CLOCKWISE,
        InputId::KNOB_4_CLOCKWISE,
        InputId::KNOB_1_COUNTER_CLOCKWISE,
        InputId::KNOB_2_COUNTER_CLOCKWISE,
        InputId::KNOB_3_COUNTER_CLOCKWISE,
        InputId::KNOB_4_COUNTER_CLOCKWISE,
        InputId::KNOB_1_PRESSED,
        InputId::KNOB_2_PRESSED,
        InputId::KNOB_3_PRESSED,
        InputId::KNOB_4_PRESSED,
        InputId::TOUCHSCREEN_ZONE_1_PRESSED,
        InputId::TOUCHSCREEN_ZONE_2_PRESSED,
        InputId::TOUCHSCREEN_ZONE_3_PRESSED,
        InputId::TOUCHSCREEN_ZONE_4_PRESSED,
        InputId::TOUCHSCREEN_SWIPED_LEFT,
        InputId::TOUCHSCREEN_SWIPED_RIGHT,
    ];
}

impl ::protobuf::EnumFull for InputId {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("InputId").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for InputId {
    fn default() -> Self {
        InputId::INPUT_ACTION_UNSPECIFIED
    }
}

impl InputId {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<InputId>("InputId")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ccommands/common/inputs.proto*\xc6\x07\n\x07InputId\x12\x1c\n\x18IN\
    PUT_ACTION_UNSPECIFIED\x10\0\x12\x14\n\x10BUTTON_1_PRESSED\x10\x01\x12\
    \x14\n\x10BUTTON_2_PRESSED\x10\x02\x12\x14\n\x10BUTTON_3_PRESSED\x10\x03\
    \x12\x14\n\x10BUTTON_4_PRESSED\x10\x04\x12\x14\n\x10BUTTON_5_PRESSED\x10\
    \x05\x12\x14\n\x10BUTTON_6_PRESSED\x10\x06\x12\x14\n\x10BUTTON_7_PRESSED\
    \x10\x07\x12\x14\n\x10BUTTON_8_PRESSED\x10\x08\x12\x14\n\x10BUTTON_9_PRE\
    SSED\x10\t\x12\x15\n\x11BUTTON_10_PRESSED\x10\n\x12\x15\n\x11BUTTON_1_RE\
    LEASED\x10\x0b\x12\x15\n\x11BUTTON_2_RELEASED\x10\x0c\x12\x15\n\x11BUTTO\
    N_3_RELEASED\x10\r\x12\x15\n\x11BUTTON_4_RELEASED\x10\x0e\x12\x15\n\x11B\
    UTTON_5_RELEASED\x10\x0f\x12\x15\n\x11BUTTON_6_RELEASED\x10\x10\x12\x15\
    \n\x11BUTTON_7_RELEASED\x10\x11\x12\x15\n\x11BUTTON_8_RELEASED\x10\x12\
    \x12\x15\n\x11BUTTON_9_RELEASED\x10\x13\x12\x16\n\x12BUTTON_10_RELEASED\
    \x10\x14\x12\x14\n\x10KNOB_1_CLOCKWISE\x10\x15\x12\x14\n\x10KNOB_2_CLOCK\
    WISE\x10\x16\x12\x14\n\x10KNOB_3_CLOCKWISE\x10\x17\x12\x14\n\x10KNOB_4_C\
    LOCKWISE\x10\x18\x12\x1c\n\x18KNOB_1_COUNTER_CLOCKWISE\x10\x19\x12\x1c\n\
    \x18KNOB_2_COUNTER_CLOCKWISE\x10\x1a\x12\x1c\n\x18KNOB_3_COUNTER_CLOCKWI\
    SE\x10\x1b\x12\x1c\n\x18KNOB_4_COUNTER_CLOCKWISE\x10\x1c\x12\x12\n\x0eKN\
    OB_1_PRESSED\x10\x1d\x12\x12\n\x0eKNOB_2_PRESSED\x10\x1e\x12\x12\n\x0eKN\
    OB_3_PRESSED\x10\x1f\x12\x12\n\x0eKNOB_4_PRESSED\x10\x20\x12\x1e\n\x1aTO\
    UCHSCREEN_ZONE_1_PRESSED\x10!\x12\x1e\n\x1aTOUCHSCREEN_ZONE_2_PRESSED\
    \x10\"\x12\x1e\n\x1aTOUCHSCREEN_ZONE_3_PRESSED\x10#\x12\x1e\n\x1aTOUCHSC\
    REEN_ZONE_4_PRESSED\x10$\x12\x1b\n\x17TOUCHSCREEN_SWIPED_LEFT\x10%\x12\
    \x1c\n\x18TOUCHSCREEN_SWIPED_RIGHT\x10&b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(InputId::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
