// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `key_config.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:key_config.KeyConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct KeyConfig {
    // message fields
    // @@protoc_insertion_point(field:key_config.KeyConfig.input_id)
    pub input_id: ::protobuf::EnumOrUnknown<super::inputs::InputId>,
    // @@protoc_insertion_point(field:key_config.KeyConfig.actions)
    pub actions: ::std::vec::Vec<Action>,
    // special fields
    // @@protoc_insertion_point(special_field:key_config.KeyConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a KeyConfig {
    fn default() -> &'a KeyConfig {
        <KeyConfig as ::protobuf::Message>::default_instance()
    }
}

impl KeyConfig {
    pub fn new() -> KeyConfig {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "input_id",
            |m: &KeyConfig| { &m.input_id },
            |m: &mut KeyConfig| { &mut m.input_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "actions",
            |m: &KeyConfig| { &m.actions },
            |m: &mut KeyConfig| { &mut m.actions },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<KeyConfig>(
            "KeyConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for KeyConfig {
    const NAME: &'static str = "KeyConfig";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.input_id = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.actions.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.input_id != ::protobuf::EnumOrUnknown::new(super::inputs::InputId::INPUT_ACTION_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.input_id.value());
        }
        for value in &self.actions {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.input_id != ::protobuf::EnumOrUnknown::new(super::inputs::InputId::INPUT_ACTION_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.input_id))?;
        }
        for v in &self.actions {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> KeyConfig {
        KeyConfig::new()
    }

    fn clear(&mut self) {
        self.input_id = ::protobuf::EnumOrUnknown::new(super::inputs::InputId::INPUT_ACTION_UNSPECIFIED);
        self.actions.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static KeyConfig {
        static instance: KeyConfig = KeyConfig {
            input_id: ::protobuf::EnumOrUnknown::from_i32(0),
            actions: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for KeyConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("KeyConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for KeyConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KeyConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:key_config.Action)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Action {
    // message fields
    // @@protoc_insertion_point(field:key_config.Action.type)
    pub type_: ::protobuf::EnumOrUnknown<ActionType>,
    // message oneof groups
    pub action_data: ::std::option::Option<action::Action_data>,
    // special fields
    // @@protoc_insertion_point(special_field:key_config.Action.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Action {
    fn default() -> &'a Action {
        <Action as ::protobuf::Message>::default_instance()
    }
}

impl Action {
    pub fn new() -> Action {
        ::std::default::Default::default()
    }

    // .key_config.KeyAction key_action = 2;

    pub fn key_action(&self) -> &KeyAction {
        match self.action_data {
            ::std::option::Option::Some(action::Action_data::KeyAction(ref v)) => v,
            _ => <KeyAction as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_key_action(&mut self) {
        self.action_data = ::std::option::Option::None;
    }

    pub fn has_key_action(&self) -> bool {
        match self.action_data {
            ::std::option::Option::Some(action::Action_data::KeyAction(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_key_action(&mut self, v: KeyAction) {
        self.action_data = ::std::option::Option::Some(action::Action_data::KeyAction(v))
    }

    // Mutable pointer to the field.
    pub fn mut_key_action(&mut self) -> &mut KeyAction {
        if let ::std::option::Option::Some(action::Action_data::KeyAction(_)) = self.action_data {
        } else {
            self.action_data = ::std::option::Option::Some(action::Action_data::KeyAction(KeyAction::new()));
        }
        match self.action_data {
            ::std::option::Option::Some(action::Action_data::KeyAction(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_key_action(&mut self) -> KeyAction {
        if self.has_key_action() {
            match self.action_data.take() {
                ::std::option::Option::Some(action::Action_data::KeyAction(v)) => v,
                _ => panic!(),
            }
        } else {
            KeyAction::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &Action| { &m.type_ },
            |m: &mut Action| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, KeyAction>(
            "key_action",
            Action::has_key_action,
            Action::key_action,
            Action::mut_key_action,
            Action::set_key_action,
        ));
        oneofs.push(action::Action_data::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Action>(
            "Action",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Action {
    const NAME: &'static str = "Action";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.action_data = ::std::option::Option::Some(action::Action_data::KeyAction(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.type_ != ::protobuf::EnumOrUnknown::new(ActionType::ACTION_TYPE_KEY) {
            my_size += ::protobuf::rt::int32_size(1, self.type_.value());
        }
        if let ::std::option::Option::Some(ref v) = self.action_data {
            match v {
                &action::Action_data::KeyAction(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.type_ != ::protobuf::EnumOrUnknown::new(ActionType::ACTION_TYPE_KEY) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if let ::std::option::Option::Some(ref v) = self.action_data {
            match v {
                &action::Action_data::KeyAction(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Action {
        Action::new()
    }

    fn clear(&mut self) {
        self.type_ = ::protobuf::EnumOrUnknown::new(ActionType::ACTION_TYPE_KEY);
        self.action_data = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Action {
        static instance: Action = Action {
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            action_data: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Action {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Action").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Action {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Action {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `Action`
pub mod action {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:key_config.Action.action_data)
    pub enum Action_data {
        // @@protoc_insertion_point(oneof_field:key_config.Action.key_action)
        KeyAction(super::KeyAction),
    }

    impl ::protobuf::Oneof for Action_data {
    }

    impl ::protobuf::OneofFull for Action_data {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::Action as ::protobuf::MessageFull>::descriptor().oneof_by_name("action_data").unwrap()).clone()
        }
    }

    impl Action_data {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Action_data>("action_data")
        }
    }
}

// @@protoc_insertion_point(message:key_config.KeyAction)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct KeyAction {
    // message fields
    // @@protoc_insertion_point(field:key_config.KeyAction.key)
    pub key: ::protobuf::EnumOrUnknown<super::keys::Key>,
    // @@protoc_insertion_point(field:key_config.KeyAction.event_type)
    pub event_type: ::protobuf::EnumOrUnknown<KeyEventType>,
    // @@protoc_insertion_point(field:key_config.KeyAction.unicode)
    pub unicode: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:key_config.KeyAction.other_key_code)
    pub other_key_code: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:key_config.KeyAction.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a KeyAction {
    fn default() -> &'a KeyAction {
        <KeyAction as ::protobuf::Message>::default_instance()
    }
}

impl KeyAction {
    pub fn new() -> KeyAction {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "key",
            |m: &KeyAction| { &m.key },
            |m: &mut KeyAction| { &mut m.key },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "event_type",
            |m: &KeyAction| { &m.event_type },
            |m: &mut KeyAction| { &mut m.event_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "unicode",
            |m: &KeyAction| { &m.unicode },
            |m: &mut KeyAction| { &mut m.unicode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "other_key_code",
            |m: &KeyAction| { &m.other_key_code },
            |m: &mut KeyAction| { &mut m.other_key_code },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<KeyAction>(
            "KeyAction",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for KeyAction {
    const NAME: &'static str = "KeyAction";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.key = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.event_type = is.read_enum_or_unknown()?;
                },
                24 => {
                    self.unicode = ::std::option::Option::Some(is.read_uint32()?);
                },
                32 => {
                    self.other_key_code = ::std::option::Option::Some(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.key != ::protobuf::EnumOrUnknown::new(super::keys::Key::KEY_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.key.value());
        }
        if self.event_type != ::protobuf::EnumOrUnknown::new(KeyEventType::KEY_EVENT_TYPE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(2, self.event_type.value());
        }
        if let Some(v) = self.unicode {
            my_size += ::protobuf::rt::uint32_size(3, v);
        }
        if let Some(v) = self.other_key_code {
            my_size += ::protobuf::rt::uint32_size(4, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.key != ::protobuf::EnumOrUnknown::new(super::keys::Key::KEY_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.key))?;
        }
        if self.event_type != ::protobuf::EnumOrUnknown::new(KeyEventType::KEY_EVENT_TYPE_UNSPECIFIED) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.event_type))?;
        }
        if let Some(v) = self.unicode {
            os.write_uint32(3, v)?;
        }
        if let Some(v) = self.other_key_code {
            os.write_uint32(4, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> KeyAction {
        KeyAction::new()
    }

    fn clear(&mut self) {
        self.key = ::protobuf::EnumOrUnknown::new(super::keys::Key::KEY_UNSPECIFIED);
        self.event_type = ::protobuf::EnumOrUnknown::new(KeyEventType::KEY_EVENT_TYPE_UNSPECIFIED);
        self.unicode = ::std::option::Option::None;
        self.other_key_code = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static KeyAction {
        static instance: KeyAction = KeyAction {
            key: ::protobuf::EnumOrUnknown::from_i32(0),
            event_type: ::protobuf::EnumOrUnknown::from_i32(0),
            unicode: ::std::option::Option::None,
            other_key_code: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for KeyAction {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("KeyAction").unwrap()).clone()
    }
}

impl ::std::fmt::Display for KeyAction {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KeyAction {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:key_config.ActionType)
pub enum ActionType {
    // @@protoc_insertion_point(enum_value:key_config.ActionType.ACTION_TYPE_KEY)
    ACTION_TYPE_KEY = 0,
}

impl ::protobuf::Enum for ActionType {
    const NAME: &'static str = "ActionType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ActionType> {
        match value {
            0 => ::std::option::Option::Some(ActionType::ACTION_TYPE_KEY),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ActionType> {
        match str {
            "ACTION_TYPE_KEY" => ::std::option::Option::Some(ActionType::ACTION_TYPE_KEY),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ActionType] = &[
        ActionType::ACTION_TYPE_KEY,
    ];
}

impl ::protobuf::EnumFull for ActionType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ActionType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ActionType {
    fn default() -> Self {
        ActionType::ACTION_TYPE_KEY
    }
}

impl ActionType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ActionType>("ActionType")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:key_config.KeyEventType)
pub enum KeyEventType {
    // @@protoc_insertion_point(enum_value:key_config.KeyEventType.KEY_EVENT_TYPE_UNSPECIFIED)
    KEY_EVENT_TYPE_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:key_config.KeyEventType.KEY_EVENT_TYPE_PRESS)
    KEY_EVENT_TYPE_PRESS = 1,
    // @@protoc_insertion_point(enum_value:key_config.KeyEventType.KEY_EVENT_TYPE_RELEASE)
    KEY_EVENT_TYPE_RELEASE = 2,
    // @@protoc_insertion_point(enum_value:key_config.KeyEventType.KEY_EVENT_TYPE_PRESS_AND_RELEASE)
    KEY_EVENT_TYPE_PRESS_AND_RELEASE = 3,
}

impl ::protobuf::Enum for KeyEventType {
    const NAME: &'static str = "KeyEventType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<KeyEventType> {
        match value {
            0 => ::std::option::Option::Some(KeyEventType::KEY_EVENT_TYPE_UNSPECIFIED),
            1 => ::std::option::Option::Some(KeyEventType::KEY_EVENT_TYPE_PRESS),
            2 => ::std::option::Option::Some(KeyEventType::KEY_EVENT_TYPE_RELEASE),
            3 => ::std::option::Option::Some(KeyEventType::KEY_EVENT_TYPE_PRESS_AND_RELEASE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<KeyEventType> {
        match str {
            "KEY_EVENT_TYPE_UNSPECIFIED" => ::std::option::Option::Some(KeyEventType::KEY_EVENT_TYPE_UNSPECIFIED),
            "KEY_EVENT_TYPE_PRESS" => ::std::option::Option::Some(KeyEventType::KEY_EVENT_TYPE_PRESS),
            "KEY_EVENT_TYPE_RELEASE" => ::std::option::Option::Some(KeyEventType::KEY_EVENT_TYPE_RELEASE),
            "KEY_EVENT_TYPE_PRESS_AND_RELEASE" => ::std::option::Option::Some(KeyEventType::KEY_EVENT_TYPE_PRESS_AND_RELEASE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [KeyEventType] = &[
        KeyEventType::KEY_EVENT_TYPE_UNSPECIFIED,
        KeyEventType::KEY_EVENT_TYPE_PRESS,
        KeyEventType::KEY_EVENT_TYPE_RELEASE,
        KeyEventType::KEY_EVENT_TYPE_PRESS_AND_RELEASE,
    ];
}

impl ::protobuf::EnumFull for KeyEventType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("KeyEventType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for KeyEventType {
    fn default() -> Self {
        KeyEventType::KEY_EVENT_TYPE_UNSPECIFIED
    }
}

impl KeyEventType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<KeyEventType>("KeyEventType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10key_config.proto\x12\nkey_config\x1a\x11common/keys.proto\x1a\x13c\
    ommon/inputs.proto\"^\n\tKeyConfig\x12#\n\x08input_id\x18\x01\x20\x01(\
    \x0e2\x08.InputIdR\x07inputId\x12,\n\x07actions\x18\x02\x20\x03(\x0b2\
    \x12.key_config.ActionR\x07actions\"{\n\x06Action\x12*\n\x04type\x18\x01\
    \x20\x01(\x0e2\x16.key_config.ActionTypeR\x04type\x126\n\nkey_action\x18\
    \x02\x20\x01(\x0b2\x15.key_config.KeyActionH\0R\tkeyActionB\r\n\x0bactio\
    n_data\"\xc5\x01\n\tKeyAction\x12\x16\n\x03key\x18\x01\x20\x01(\x0e2\x04\
    .KeyR\x03key\x127\n\nevent_type\x18\x02\x20\x01(\x0e2\x18.key_config.Key\
    EventTypeR\teventType\x12\x1d\n\x07unicode\x18\x03\x20\x01(\rH\0R\x07uni\
    code\x88\x01\x01\x12)\n\x0eother_key_code\x18\x04\x20\x01(\rH\x01R\x0cot\
    herKeyCode\x88\x01\x01B\n\n\x08_unicodeB\x11\n\x0f_other_key_code*!\n\nA\
    ctionType\x12\x13\n\x0fACTION_TYPE_KEY\x10\0*\x8a\x01\n\x0cKeyEventType\
    \x12\x1e\n\x1aKEY_EVENT_TYPE_UNSPECIFIED\x10\0\x12\x18\n\x14KEY_EVENT_TY\
    PE_PRESS\x10\x01\x12\x1a\n\x16KEY_EVENT_TYPE_RELEASE\x10\x02\x12$\n\x20K\
    EY_EVENT_TYPE_PRESS_AND_RELEASE\x10\x03b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::keys::file_descriptor().clone());
            deps.push(super::inputs::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(KeyConfig::generated_message_descriptor_data());
            messages.push(Action::generated_message_descriptor_data());
            messages.push(KeyAction::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(ActionType::generated_enum_descriptor_data());
            enums.push(KeyEventType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
