// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `common/keys.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:Key)
pub enum Key {
    // @@protoc_insertion_point(enum_value:Key.KEY_UNSPECIFIED)
    KEY_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:Key.KEY_ADD)
    KEY_ADD = 1,
    // @@protoc_insertion_point(enum_value:Key.KEY_ALT)
    KEY_ALT = 2,
    // @@protoc_insertion_point(enum_value:Key.KEY_BACKSPACE)
    KEY_BACKSPACE = 3,
    // @@protoc_insertion_point(enum_value:Key.KEY_BREAK)
    KEY_BREAK = 4,
    // @@protoc_insertion_point(enum_value:Key.KEY_BEGIN)
    KEY_BEGIN = 5,
    // @@protoc_insertion_point(enum_value:Key.KEY_CANCEL)
    KEY_CANCEL = 6,
    // @@protoc_insertion_point(enum_value:Key.KEY_CAPS_LOCK)
    KEY_CAPS_LOCK = 7,
    // @@protoc_insertion_point(enum_value:Key.KEY_CLEAR)
    KEY_CLEAR = 8,
    // @@protoc_insertion_point(enum_value:Key.KEY_COMMAND)
    KEY_COMMAND = 9,
    // @@protoc_insertion_point(enum_value:Key.KEY_CONTROL)
    KEY_CONTROL = 10,
    // @@protoc_insertion_point(enum_value:Key.KEY_DECIMAL)
    KEY_DECIMAL = 11,
    // @@protoc_insertion_point(enum_value:Key.KEY_DELETE)
    KEY_DELETE = 12,
    // @@protoc_insertion_point(enum_value:Key.KEY_DIVIDE)
    KEY_DIVIDE = 13,
    // @@protoc_insertion_point(enum_value:Key.KEY_DOWN_ARROW)
    KEY_DOWN_ARROW = 14,
    // @@protoc_insertion_point(enum_value:Key.KEY_END)
    KEY_END = 15,
    // @@protoc_insertion_point(enum_value:Key.KEY_ESCAPE)
    KEY_ESCAPE = 16,
    // @@protoc_insertion_point(enum_value:Key.KEY_EXECUTE)
    KEY_EXECUTE = 17,
    // @@protoc_insertion_point(enum_value:Key.KEY_F1)
    KEY_F1 = 18,
    // @@protoc_insertion_point(enum_value:Key.KEY_F2)
    KEY_F2 = 19,
    // @@protoc_insertion_point(enum_value:Key.KEY_F3)
    KEY_F3 = 20,
    // @@protoc_insertion_point(enum_value:Key.KEY_F4)
    KEY_F4 = 21,
    // @@protoc_insertion_point(enum_value:Key.KEY_F5)
    KEY_F5 = 22,
    // @@protoc_insertion_point(enum_value:Key.KEY_F6)
    KEY_F6 = 23,
    // @@protoc_insertion_point(enum_value:Key.KEY_F7)
    KEY_F7 = 24,
    // @@protoc_insertion_point(enum_value:Key.KEY_F8)
    KEY_F8 = 25,
    // @@protoc_insertion_point(enum_value:Key.KEY_F9)
    KEY_F9 = 26,
    // @@protoc_insertion_point(enum_value:Key.KEY_F10)
    KEY_F10 = 27,
    // @@protoc_insertion_point(enum_value:Key.KEY_F11)
    KEY_F11 = 28,
    // @@protoc_insertion_point(enum_value:Key.KEY_F12)
    KEY_F12 = 29,
    // @@protoc_insertion_point(enum_value:Key.KEY_F13)
    KEY_F13 = 30,
    // @@protoc_insertion_point(enum_value:Key.KEY_F14)
    KEY_F14 = 31,
    // @@protoc_insertion_point(enum_value:Key.KEY_F15)
    KEY_F15 = 32,
    // @@protoc_insertion_point(enum_value:Key.KEY_F16)
    KEY_F16 = 33,
    // @@protoc_insertion_point(enum_value:Key.KEY_F17)
    KEY_F17 = 34,
    // @@protoc_insertion_point(enum_value:Key.KEY_F18)
    KEY_F18 = 35,
    // @@protoc_insertion_point(enum_value:Key.KEY_F19)
    KEY_F19 = 36,
    // @@protoc_insertion_point(enum_value:Key.KEY_F20)
    KEY_F20 = 37,
    // @@protoc_insertion_point(enum_value:Key.KEY_F21)
    KEY_F21 = 38,
    // @@protoc_insertion_point(enum_value:Key.KEY_F22)
    KEY_F22 = 39,
    // @@protoc_insertion_point(enum_value:Key.KEY_F23)
    KEY_F23 = 40,
    // @@protoc_insertion_point(enum_value:Key.KEY_F24)
    KEY_F24 = 41,
    // @@protoc_insertion_point(enum_value:Key.KEY_F25)
    KEY_F25 = 42,
    // @@protoc_insertion_point(enum_value:Key.KEY_F26)
    KEY_F26 = 43,
    // @@protoc_insertion_point(enum_value:Key.KEY_F27)
    KEY_F27 = 44,
    // @@protoc_insertion_point(enum_value:Key.KEY_F28)
    KEY_F28 = 45,
    // @@protoc_insertion_point(enum_value:Key.KEY_F29)
    KEY_F29 = 46,
    // @@protoc_insertion_point(enum_value:Key.KEY_F30)
    KEY_F30 = 47,
    // @@protoc_insertion_point(enum_value:Key.KEY_F31)
    KEY_F31 = 48,
    // @@protoc_insertion_point(enum_value:Key.KEY_F32)
    KEY_F32 = 49,
    // @@protoc_insertion_point(enum_value:Key.KEY_F33)
    KEY_F33 = 50,
    // @@protoc_insertion_point(enum_value:Key.KEY_F34)
    KEY_F34 = 51,
    // @@protoc_insertion_point(enum_value:Key.KEY_F35)
    KEY_F35 = 52,
    // @@protoc_insertion_point(enum_value:Key.KEY_FIND)
    KEY_FIND = 53,
    // @@protoc_insertion_point(enum_value:Key.KEY_HANGUL)
    KEY_HANGUL = 54,
    // @@protoc_insertion_point(enum_value:Key.KEY_HANJA)
    KEY_HANJA = 55,
    // @@protoc_insertion_point(enum_value:Key.KEY_HELP)
    KEY_HELP = 56,
    // @@protoc_insertion_point(enum_value:Key.KEY_HOME)
    KEY_HOME = 57,
    // @@protoc_insertion_point(enum_value:Key.KEY_INSERT)
    KEY_INSERT = 58,
    // @@protoc_insertion_point(enum_value:Key.KEY_KANJI)
    KEY_KANJI = 59,
    // @@protoc_insertion_point(enum_value:Key.KEY_L_CONTROL)
    KEY_L_CONTROL = 60,
    // @@protoc_insertion_point(enum_value:Key.KEY_LEFT_ARROW)
    KEY_LEFT_ARROW = 61,
    // @@protoc_insertion_point(enum_value:Key.KEY_LINEFEED)
    KEY_LINEFEED = 62,
    // @@protoc_insertion_point(enum_value:Key.KEY_L_MENU)
    KEY_L_MENU = 63,
    // @@protoc_insertion_point(enum_value:Key.KEY_L_SHIFT)
    KEY_L_SHIFT = 64,
    // @@protoc_insertion_point(enum_value:Key.KEY_MEDIA_NEXT_TRACK)
    KEY_MEDIA_NEXT_TRACK = 65,
    // @@protoc_insertion_point(enum_value:Key.KEY_MEDIA_PLAY_PAUSE)
    KEY_MEDIA_PLAY_PAUSE = 66,
    // @@protoc_insertion_point(enum_value:Key.KEY_MEDIA_PREV_TRACK)
    KEY_MEDIA_PREV_TRACK = 67,
    // @@protoc_insertion_point(enum_value:Key.KEY_MEDIA_STOP)
    KEY_MEDIA_STOP = 68,
    // @@protoc_insertion_point(enum_value:Key.KEY_META)
    KEY_META = 69,
    // @@protoc_insertion_point(enum_value:Key.KEY_MODE_CHANGE)
    KEY_MODE_CHANGE = 70,
    // @@protoc_insertion_point(enum_value:Key.KEY_MULTIPLY)
    KEY_MULTIPLY = 71,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMLOCK)
    KEY_NUMLOCK = 72,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD0)
    KEY_NUMPAD0 = 73,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD1)
    KEY_NUMPAD1 = 74,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD2)
    KEY_NUMPAD2 = 75,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD3)
    KEY_NUMPAD3 = 76,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD4)
    KEY_NUMPAD4 = 77,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD5)
    KEY_NUMPAD5 = 78,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD6)
    KEY_NUMPAD6 = 79,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD7)
    KEY_NUMPAD7 = 80,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD8)
    KEY_NUMPAD8 = 81,
    // @@protoc_insertion_point(enum_value:Key.KEY_NUMPAD9)
    KEY_NUMPAD9 = 82,
    // @@protoc_insertion_point(enum_value:Key.KEY_OPTION)
    KEY_OPTION = 83,
    // @@protoc_insertion_point(enum_value:Key.KEY_PAGE_DOWN)
    KEY_PAGE_DOWN = 84,
    // @@protoc_insertion_point(enum_value:Key.KEY_PAGE_UP)
    KEY_PAGE_UP = 85,
    // @@protoc_insertion_point(enum_value:Key.KEY_PAUSE)
    KEY_PAUSE = 86,
    // @@protoc_insertion_point(enum_value:Key.KEY_PRINT)
    KEY_PRINT = 87,
    // @@protoc_insertion_point(enum_value:Key.KEY_PRINT_SCR)
    KEY_PRINT_SCR = 88,
    // @@protoc_insertion_point(enum_value:Key.KEY_R_CONTROL)
    KEY_R_CONTROL = 89,
    // @@protoc_insertion_point(enum_value:Key.KEY_REDO)
    KEY_REDO = 90,
    // @@protoc_insertion_point(enum_value:Key.KEY_RETURN)
    KEY_RETURN = 91,
    // @@protoc_insertion_point(enum_value:Key.KEY_RIGHT_ARROW)
    KEY_RIGHT_ARROW = 92,
    // @@protoc_insertion_point(enum_value:Key.KEY_R_SHIFT)
    KEY_R_SHIFT = 93,
    // @@protoc_insertion_point(enum_value:Key.KEY_SCROLL_LOCK)
    KEY_SCROLL_LOCK = 94,
    // @@protoc_insertion_point(enum_value:Key.KEY_SELECT)
    KEY_SELECT = 95,
    // @@protoc_insertion_point(enum_value:Key.KEY_SCRIPT_SWITCH)
    KEY_SCRIPT_SWITCH = 96,
    // @@protoc_insertion_point(enum_value:Key.KEY_SHIFT)
    KEY_SHIFT = 97,
    // @@protoc_insertion_point(enum_value:Key.KEY_SHIFT_LOCK)
    KEY_SHIFT_LOCK = 98,
    // @@protoc_insertion_point(enum_value:Key.KEY_SPACE)
    KEY_SPACE = 99,
    // @@protoc_insertion_point(enum_value:Key.KEY_SUBTRACT)
    KEY_SUBTRACT = 100,
    // @@protoc_insertion_point(enum_value:Key.KEY_SUPER)
    KEY_SUPER = 101,
    // @@protoc_insertion_point(enum_value:Key.KEY_SYS_REQ)
    KEY_SYS_REQ = 102,
    // @@protoc_insertion_point(enum_value:Key.KEY_TAB)
    KEY_TAB = 103,
    // @@protoc_insertion_point(enum_value:Key.KEY_UNDO)
    KEY_UNDO = 104,
    // @@protoc_insertion_point(enum_value:Key.KEY_UP_ARROW)
    KEY_UP_ARROW = 105,
    // @@protoc_insertion_point(enum_value:Key.KEY_VOLUME_DOWN)
    KEY_VOLUME_DOWN = 106,
    // @@protoc_insertion_point(enum_value:Key.KEY_VOLUME_MUTE)
    KEY_VOLUME_MUTE = 107,
    // @@protoc_insertion_point(enum_value:Key.KEY_VOLUME_UP)
    KEY_VOLUME_UP = 108,
    // @@protoc_insertion_point(enum_value:Key.KEY_MIC_MUTE)
    KEY_MIC_MUTE = 109,
    // @@protoc_insertion_point(enum_value:Key.KEY_WINDOWS)
    KEY_WINDOWS = 110,
    // @@protoc_insertion_point(enum_value:Key.KEY_UNICODE)
    KEY_UNICODE = 111,
    // @@protoc_insertion_point(enum_value:Key.KEY_OTHER)
    KEY_OTHER = 112,
}

impl ::protobuf::Enum for Key {
    const NAME: &'static str = "Key";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Key> {
        match value {
            0 => ::std::option::Option::Some(Key::KEY_UNSPECIFIED),
            1 => ::std::option::Option::Some(Key::KEY_ADD),
            2 => ::std::option::Option::Some(Key::KEY_ALT),
            3 => ::std::option::Option::Some(Key::KEY_BACKSPACE),
            4 => ::std::option::Option::Some(Key::KEY_BREAK),
            5 => ::std::option::Option::Some(Key::KEY_BEGIN),
            6 => ::std::option::Option::Some(Key::KEY_CANCEL),
            7 => ::std::option::Option::Some(Key::KEY_CAPS_LOCK),
            8 => ::std::option::Option::Some(Key::KEY_CLEAR),
            9 => ::std::option::Option::Some(Key::KEY_COMMAND),
            10 => ::std::option::Option::Some(Key::KEY_CONTROL),
            11 => ::std::option::Option::Some(Key::KEY_DECIMAL),
            12 => ::std::option::Option::Some(Key::KEY_DELETE),
            13 => ::std::option::Option::Some(Key::KEY_DIVIDE),
            14 => ::std::option::Option::Some(Key::KEY_DOWN_ARROW),
            15 => ::std::option::Option::Some(Key::KEY_END),
            16 => ::std::option::Option::Some(Key::KEY_ESCAPE),
            17 => ::std::option::Option::Some(Key::KEY_EXECUTE),
            18 => ::std::option::Option::Some(Key::KEY_F1),
            19 => ::std::option::Option::Some(Key::KEY_F2),
            20 => ::std::option::Option::Some(Key::KEY_F3),
            21 => ::std::option::Option::Some(Key::KEY_F4),
            22 => ::std::option::Option::Some(Key::KEY_F5),
            23 => ::std::option::Option::Some(Key::KEY_F6),
            24 => ::std::option::Option::Some(Key::KEY_F7),
            25 => ::std::option::Option::Some(Key::KEY_F8),
            26 => ::std::option::Option::Some(Key::KEY_F9),
            27 => ::std::option::Option::Some(Key::KEY_F10),
            28 => ::std::option::Option::Some(Key::KEY_F11),
            29 => ::std::option::Option::Some(Key::KEY_F12),
            30 => ::std::option::Option::Some(Key::KEY_F13),
            31 => ::std::option::Option::Some(Key::KEY_F14),
            32 => ::std::option::Option::Some(Key::KEY_F15),
            33 => ::std::option::Option::Some(Key::KEY_F16),
            34 => ::std::option::Option::Some(Key::KEY_F17),
            35 => ::std::option::Option::Some(Key::KEY_F18),
            36 => ::std::option::Option::Some(Key::KEY_F19),
            37 => ::std::option::Option::Some(Key::KEY_F20),
            38 => ::std::option::Option::Some(Key::KEY_F21),
            39 => ::std::option::Option::Some(Key::KEY_F22),
            40 => ::std::option::Option::Some(Key::KEY_F23),
            41 => ::std::option::Option::Some(Key::KEY_F24),
            42 => ::std::option::Option::Some(Key::KEY_F25),
            43 => ::std::option::Option::Some(Key::KEY_F26),
            44 => ::std::option::Option::Some(Key::KEY_F27),
            45 => ::std::option::Option::Some(Key::KEY_F28),
            46 => ::std::option::Option::Some(Key::KEY_F29),
            47 => ::std::option::Option::Some(Key::KEY_F30),
            48 => ::std::option::Option::Some(Key::KEY_F31),
            49 => ::std::option::Option::Some(Key::KEY_F32),
            50 => ::std::option::Option::Some(Key::KEY_F33),
            51 => ::std::option::Option::Some(Key::KEY_F34),
            52 => ::std::option::Option::Some(Key::KEY_F35),
            53 => ::std::option::Option::Some(Key::KEY_FIND),
            54 => ::std::option::Option::Some(Key::KEY_HANGUL),
            55 => ::std::option::Option::Some(Key::KEY_HANJA),
            56 => ::std::option::Option::Some(Key::KEY_HELP),
            57 => ::std::option::Option::Some(Key::KEY_HOME),
            58 => ::std::option::Option::Some(Key::KEY_INSERT),
            59 => ::std::option::Option::Some(Key::KEY_KANJI),
            60 => ::std::option::Option::Some(Key::KEY_L_CONTROL),
            61 => ::std::option::Option::Some(Key::KEY_LEFT_ARROW),
            62 => ::std::option::Option::Some(Key::KEY_LINEFEED),
            63 => ::std::option::Option::Some(Key::KEY_L_MENU),
            64 => ::std::option::Option::Some(Key::KEY_L_SHIFT),
            65 => ::std::option::Option::Some(Key::KEY_MEDIA_NEXT_TRACK),
            66 => ::std::option::Option::Some(Key::KEY_MEDIA_PLAY_PAUSE),
            67 => ::std::option::Option::Some(Key::KEY_MEDIA_PREV_TRACK),
            68 => ::std::option::Option::Some(Key::KEY_MEDIA_STOP),
            69 => ::std::option::Option::Some(Key::KEY_META),
            70 => ::std::option::Option::Some(Key::KEY_MODE_CHANGE),
            71 => ::std::option::Option::Some(Key::KEY_MULTIPLY),
            72 => ::std::option::Option::Some(Key::KEY_NUMLOCK),
            73 => ::std::option::Option::Some(Key::KEY_NUMPAD0),
            74 => ::std::option::Option::Some(Key::KEY_NUMPAD1),
            75 => ::std::option::Option::Some(Key::KEY_NUMPAD2),
            76 => ::std::option::Option::Some(Key::KEY_NUMPAD3),
            77 => ::std::option::Option::Some(Key::KEY_NUMPAD4),
            78 => ::std::option::Option::Some(Key::KEY_NUMPAD5),
            79 => ::std::option::Option::Some(Key::KEY_NUMPAD6),
            80 => ::std::option::Option::Some(Key::KEY_NUMPAD7),
            81 => ::std::option::Option::Some(Key::KEY_NUMPAD8),
            82 => ::std::option::Option::Some(Key::KEY_NUMPAD9),
            83 => ::std::option::Option::Some(Key::KEY_OPTION),
            84 => ::std::option::Option::Some(Key::KEY_PAGE_DOWN),
            85 => ::std::option::Option::Some(Key::KEY_PAGE_UP),
            86 => ::std::option::Option::Some(Key::KEY_PAUSE),
            87 => ::std::option::Option::Some(Key::KEY_PRINT),
            88 => ::std::option::Option::Some(Key::KEY_PRINT_SCR),
            89 => ::std::option::Option::Some(Key::KEY_R_CONTROL),
            90 => ::std::option::Option::Some(Key::KEY_REDO),
            91 => ::std::option::Option::Some(Key::KEY_RETURN),
            92 => ::std::option::Option::Some(Key::KEY_RIGHT_ARROW),
            93 => ::std::option::Option::Some(Key::KEY_R_SHIFT),
            94 => ::std::option::Option::Some(Key::KEY_SCROLL_LOCK),
            95 => ::std::option::Option::Some(Key::KEY_SELECT),
            96 => ::std::option::Option::Some(Key::KEY_SCRIPT_SWITCH),
            97 => ::std::option::Option::Some(Key::KEY_SHIFT),
            98 => ::std::option::Option::Some(Key::KEY_SHIFT_LOCK),
            99 => ::std::option::Option::Some(Key::KEY_SPACE),
            100 => ::std::option::Option::Some(Key::KEY_SUBTRACT),
            101 => ::std::option::Option::Some(Key::KEY_SUPER),
            102 => ::std::option::Option::Some(Key::KEY_SYS_REQ),
            103 => ::std::option::Option::Some(Key::KEY_TAB),
            104 => ::std::option::Option::Some(Key::KEY_UNDO),
            105 => ::std::option::Option::Some(Key::KEY_UP_ARROW),
            106 => ::std::option::Option::Some(Key::KEY_VOLUME_DOWN),
            107 => ::std::option::Option::Some(Key::KEY_VOLUME_MUTE),
            108 => ::std::option::Option::Some(Key::KEY_VOLUME_UP),
            109 => ::std::option::Option::Some(Key::KEY_MIC_MUTE),
            110 => ::std::option::Option::Some(Key::KEY_WINDOWS),
            111 => ::std::option::Option::Some(Key::KEY_UNICODE),
            112 => ::std::option::Option::Some(Key::KEY_OTHER),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<Key> {
        match str {
            "KEY_UNSPECIFIED" => ::std::option::Option::Some(Key::KEY_UNSPECIFIED),
            "KEY_ADD" => ::std::option::Option::Some(Key::KEY_ADD),
            "KEY_ALT" => ::std::option::Option::Some(Key::KEY_ALT),
            "KEY_BACKSPACE" => ::std::option::Option::Some(Key::KEY_BACKSPACE),
            "KEY_BREAK" => ::std::option::Option::Some(Key::KEY_BREAK),
            "KEY_BEGIN" => ::std::option::Option::Some(Key::KEY_BEGIN),
            "KEY_CANCEL" => ::std::option::Option::Some(Key::KEY_CANCEL),
            "KEY_CAPS_LOCK" => ::std::option::Option::Some(Key::KEY_CAPS_LOCK),
            "KEY_CLEAR" => ::std::option::Option::Some(Key::KEY_CLEAR),
            "KEY_COMMAND" => ::std::option::Option::Some(Key::KEY_COMMAND),
            "KEY_CONTROL" => ::std::option::Option::Some(Key::KEY_CONTROL),
            "KEY_DECIMAL" => ::std::option::Option::Some(Key::KEY_DECIMAL),
            "KEY_DELETE" => ::std::option::Option::Some(Key::KEY_DELETE),
            "KEY_DIVIDE" => ::std::option::Option::Some(Key::KEY_DIVIDE),
            "KEY_DOWN_ARROW" => ::std::option::Option::Some(Key::KEY_DOWN_ARROW),
            "KEY_END" => ::std::option::Option::Some(Key::KEY_END),
            "KEY_ESCAPE" => ::std::option::Option::Some(Key::KEY_ESCAPE),
            "KEY_EXECUTE" => ::std::option::Option::Some(Key::KEY_EXECUTE),
            "KEY_F1" => ::std::option::Option::Some(Key::KEY_F1),
            "KEY_F2" => ::std::option::Option::Some(Key::KEY_F2),
            "KEY_F3" => ::std::option::Option::Some(Key::KEY_F3),
            "KEY_F4" => ::std::option::Option::Some(Key::KEY_F4),
            "KEY_F5" => ::std::option::Option::Some(Key::KEY_F5),
            "KEY_F6" => ::std::option::Option::Some(Key::KEY_F6),
            "KEY_F7" => ::std::option::Option::Some(Key::KEY_F7),
            "KEY_F8" => ::std::option::Option::Some(Key::KEY_F8),
            "KEY_F9" => ::std::option::Option::Some(Key::KEY_F9),
            "KEY_F10" => ::std::option::Option::Some(Key::KEY_F10),
            "KEY_F11" => ::std::option::Option::Some(Key::KEY_F11),
            "KEY_F12" => ::std::option::Option::Some(Key::KEY_F12),
            "KEY_F13" => ::std::option::Option::Some(Key::KEY_F13),
            "KEY_F14" => ::std::option::Option::Some(Key::KEY_F14),
            "KEY_F15" => ::std::option::Option::Some(Key::KEY_F15),
            "KEY_F16" => ::std::option::Option::Some(Key::KEY_F16),
            "KEY_F17" => ::std::option::Option::Some(Key::KEY_F17),
            "KEY_F18" => ::std::option::Option::Some(Key::KEY_F18),
            "KEY_F19" => ::std::option::Option::Some(Key::KEY_F19),
            "KEY_F20" => ::std::option::Option::Some(Key::KEY_F20),
            "KEY_F21" => ::std::option::Option::Some(Key::KEY_F21),
            "KEY_F22" => ::std::option::Option::Some(Key::KEY_F22),
            "KEY_F23" => ::std::option::Option::Some(Key::KEY_F23),
            "KEY_F24" => ::std::option::Option::Some(Key::KEY_F24),
            "KEY_F25" => ::std::option::Option::Some(Key::KEY_F25),
            "KEY_F26" => ::std::option::Option::Some(Key::KEY_F26),
            "KEY_F27" => ::std::option::Option::Some(Key::KEY_F27),
            "KEY_F28" => ::std::option::Option::Some(Key::KEY_F28),
            "KEY_F29" => ::std::option::Option::Some(Key::KEY_F29),
            "KEY_F30" => ::std::option::Option::Some(Key::KEY_F30),
            "KEY_F31" => ::std::option::Option::Some(Key::KEY_F31),
            "KEY_F32" => ::std::option::Option::Some(Key::KEY_F32),
            "KEY_F33" => ::std::option::Option::Some(Key::KEY_F33),
            "KEY_F34" => ::std::option::Option::Some(Key::KEY_F34),
            "KEY_F35" => ::std::option::Option::Some(Key::KEY_F35),
            "KEY_FIND" => ::std::option::Option::Some(Key::KEY_FIND),
            "KEY_HANGUL" => ::std::option::Option::Some(Key::KEY_HANGUL),
            "KEY_HANJA" => ::std::option::Option::Some(Key::KEY_HANJA),
            "KEY_HELP" => ::std::option::Option::Some(Key::KEY_HELP),
            "KEY_HOME" => ::std::option::Option::Some(Key::KEY_HOME),
            "KEY_INSERT" => ::std::option::Option::Some(Key::KEY_INSERT),
            "KEY_KANJI" => ::std::option::Option::Some(Key::KEY_KANJI),
            "KEY_L_CONTROL" => ::std::option::Option::Some(Key::KEY_L_CONTROL),
            "KEY_LEFT_ARROW" => ::std::option::Option::Some(Key::KEY_LEFT_ARROW),
            "KEY_LINEFEED" => ::std::option::Option::Some(Key::KEY_LINEFEED),
            "KEY_L_MENU" => ::std::option::Option::Some(Key::KEY_L_MENU),
            "KEY_L_SHIFT" => ::std::option::Option::Some(Key::KEY_L_SHIFT),
            "KEY_MEDIA_NEXT_TRACK" => ::std::option::Option::Some(Key::KEY_MEDIA_NEXT_TRACK),
            "KEY_MEDIA_PLAY_PAUSE" => ::std::option::Option::Some(Key::KEY_MEDIA_PLAY_PAUSE),
            "KEY_MEDIA_PREV_TRACK" => ::std::option::Option::Some(Key::KEY_MEDIA_PREV_TRACK),
            "KEY_MEDIA_STOP" => ::std::option::Option::Some(Key::KEY_MEDIA_STOP),
            "KEY_META" => ::std::option::Option::Some(Key::KEY_META),
            "KEY_MODE_CHANGE" => ::std::option::Option::Some(Key::KEY_MODE_CHANGE),
            "KEY_MULTIPLY" => ::std::option::Option::Some(Key::KEY_MULTIPLY),
            "KEY_NUMLOCK" => ::std::option::Option::Some(Key::KEY_NUMLOCK),
            "KEY_NUMPAD0" => ::std::option::Option::Some(Key::KEY_NUMPAD0),
            "KEY_NUMPAD1" => ::std::option::Option::Some(Key::KEY_NUMPAD1),
            "KEY_NUMPAD2" => ::std::option::Option::Some(Key::KEY_NUMPAD2),
            "KEY_NUMPAD3" => ::std::option::Option::Some(Key::KEY_NUMPAD3),
            "KEY_NUMPAD4" => ::std::option::Option::Some(Key::KEY_NUMPAD4),
            "KEY_NUMPAD5" => ::std::option::Option::Some(Key::KEY_NUMPAD5),
            "KEY_NUMPAD6" => ::std::option::Option::Some(Key::KEY_NUMPAD6),
            "KEY_NUMPAD7" => ::std::option::Option::Some(Key::KEY_NUMPAD7),
            "KEY_NUMPAD8" => ::std::option::Option::Some(Key::KEY_NUMPAD8),
            "KEY_NUMPAD9" => ::std::option::Option::Some(Key::KEY_NUMPAD9),
            "KEY_OPTION" => ::std::option::Option::Some(Key::KEY_OPTION),
            "KEY_PAGE_DOWN" => ::std::option::Option::Some(Key::KEY_PAGE_DOWN),
            "KEY_PAGE_UP" => ::std::option::Option::Some(Key::KEY_PAGE_UP),
            "KEY_PAUSE" => ::std::option::Option::Some(Key::KEY_PAUSE),
            "KEY_PRINT" => ::std::option::Option::Some(Key::KEY_PRINT),
            "KEY_PRINT_SCR" => ::std::option::Option::Some(Key::KEY_PRINT_SCR),
            "KEY_R_CONTROL" => ::std::option::Option::Some(Key::KEY_R_CONTROL),
            "KEY_REDO" => ::std::option::Option::Some(Key::KEY_REDO),
            "KEY_RETURN" => ::std::option::Option::Some(Key::KEY_RETURN),
            "KEY_RIGHT_ARROW" => ::std::option::Option::Some(Key::KEY_RIGHT_ARROW),
            "KEY_R_SHIFT" => ::std::option::Option::Some(Key::KEY_R_SHIFT),
            "KEY_SCROLL_LOCK" => ::std::option::Option::Some(Key::KEY_SCROLL_LOCK),
            "KEY_SELECT" => ::std::option::Option::Some(Key::KEY_SELECT),
            "KEY_SCRIPT_SWITCH" => ::std::option::Option::Some(Key::KEY_SCRIPT_SWITCH),
            "KEY_SHIFT" => ::std::option::Option::Some(Key::KEY_SHIFT),
            "KEY_SHIFT_LOCK" => ::std::option::Option::Some(Key::KEY_SHIFT_LOCK),
            "KEY_SPACE" => ::std::option::Option::Some(Key::KEY_SPACE),
            "KEY_SUBTRACT" => ::std::option::Option::Some(Key::KEY_SUBTRACT),
            "KEY_SUPER" => ::std::option::Option::Some(Key::KEY_SUPER),
            "KEY_SYS_REQ" => ::std::option::Option::Some(Key::KEY_SYS_REQ),
            "KEY_TAB" => ::std::option::Option::Some(Key::KEY_TAB),
            "KEY_UNDO" => ::std::option::Option::Some(Key::KEY_UNDO),
            "KEY_UP_ARROW" => ::std::option::Option::Some(Key::KEY_UP_ARROW),
            "KEY_VOLUME_DOWN" => ::std::option::Option::Some(Key::KEY_VOLUME_DOWN),
            "KEY_VOLUME_MUTE" => ::std::option::Option::Some(Key::KEY_VOLUME_MUTE),
            "KEY_VOLUME_UP" => ::std::option::Option::Some(Key::KEY_VOLUME_UP),
            "KEY_MIC_MUTE" => ::std::option::Option::Some(Key::KEY_MIC_MUTE),
            "KEY_WINDOWS" => ::std::option::Option::Some(Key::KEY_WINDOWS),
            "KEY_UNICODE" => ::std::option::Option::Some(Key::KEY_UNICODE),
            "KEY_OTHER" => ::std::option::Option::Some(Key::KEY_OTHER),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [Key] = &[
        Key::KEY_UNSPECIFIED,
        Key::KEY_ADD,
        Key::KEY_ALT,
        Key::KEY_BACKSPACE,
        Key::KEY_BREAK,
        Key::KEY_BEGIN,
        Key::KEY_CANCEL,
        Key::KEY_CAPS_LOCK,
        Key::KEY_CLEAR,
        Key::KEY_COMMAND,
        Key::KEY_CONTROL,
        Key::KEY_DECIMAL,
        Key::KEY_DELETE,
        Key::KEY_DIVIDE,
        Key::KEY_DOWN_ARROW,
        Key::KEY_END,
        Key::KEY_ESCAPE,
        Key::KEY_EXECUTE,
        Key::KEY_F1,
        Key::KEY_F2,
        Key::KEY_F3,
        Key::KEY_F4,
        Key::KEY_F5,
        Key::KEY_F6,
        Key::KEY_F7,
        Key::KEY_F8,
        Key::KEY_F9,
        Key::KEY_F10,
        Key::KEY_F11,
        Key::KEY_F12,
        Key::KEY_F13,
        Key::KEY_F14,
        Key::KEY_F15,
        Key::KEY_F16,
        Key::KEY_F17,
        Key::KEY_F18,
        Key::KEY_F19,
        Key::KEY_F20,
        Key::KEY_F21,
        Key::KEY_F22,
        Key::KEY_F23,
        Key::KEY_F24,
        Key::KEY_F25,
        Key::KEY_F26,
        Key::KEY_F27,
        Key::KEY_F28,
        Key::KEY_F29,
        Key::KEY_F30,
        Key::KEY_F31,
        Key::KEY_F32,
        Key::KEY_F33,
        Key::KEY_F34,
        Key::KEY_F35,
        Key::KEY_FIND,
        Key::KEY_HANGUL,
        Key::KEY_HANJA,
        Key::KEY_HELP,
        Key::KEY_HOME,
        Key::KEY_INSERT,
        Key::KEY_KANJI,
        Key::KEY_L_CONTROL,
        Key::KEY_LEFT_ARROW,
        Key::KEY_LINEFEED,
        Key::KEY_L_MENU,
        Key::KEY_L_SHIFT,
        Key::KEY_MEDIA_NEXT_TRACK,
        Key::KEY_MEDIA_PLAY_PAUSE,
        Key::KEY_MEDIA_PREV_TRACK,
        Key::KEY_MEDIA_STOP,
        Key::KEY_META,
        Key::KEY_MODE_CHANGE,
        Key::KEY_MULTIPLY,
        Key::KEY_NUMLOCK,
        Key::KEY_NUMPAD0,
        Key::KEY_NUMPAD1,
        Key::KEY_NUMPAD2,
        Key::KEY_NUMPAD3,
        Key::KEY_NUMPAD4,
        Key::KEY_NUMPAD5,
        Key::KEY_NUMPAD6,
        Key::KEY_NUMPAD7,
        Key::KEY_NUMPAD8,
        Key::KEY_NUMPAD9,
        Key::KEY_OPTION,
        Key::KEY_PAGE_DOWN,
        Key::KEY_PAGE_UP,
        Key::KEY_PAUSE,
        Key::KEY_PRINT,
        Key::KEY_PRINT_SCR,
        Key::KEY_R_CONTROL,
        Key::KEY_REDO,
        Key::KEY_RETURN,
        Key::KEY_RIGHT_ARROW,
        Key::KEY_R_SHIFT,
        Key::KEY_SCROLL_LOCK,
        Key::KEY_SELECT,
        Key::KEY_SCRIPT_SWITCH,
        Key::KEY_SHIFT,
        Key::KEY_SHIFT_LOCK,
        Key::KEY_SPACE,
        Key::KEY_SUBTRACT,
        Key::KEY_SUPER,
        Key::KEY_SYS_REQ,
        Key::KEY_TAB,
        Key::KEY_UNDO,
        Key::KEY_UP_ARROW,
        Key::KEY_VOLUME_DOWN,
        Key::KEY_VOLUME_MUTE,
        Key::KEY_VOLUME_UP,
        Key::KEY_MIC_MUTE,
        Key::KEY_WINDOWS,
        Key::KEY_UNICODE,
        Key::KEY_OTHER,
    ];
}

impl ::protobuf::EnumFull for Key {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("Key").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for Key {
    fn default() -> Self {
        Key::KEY_UNSPECIFIED
    }
}

impl Key {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Key>("Key")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11common/keys.proto*\x87\x0e\n\x03Key\x12\x13\n\x0fKEY_UNSPECIFIED\
    \x10\0\x12\x0b\n\x07KEY_ADD\x10\x01\x12\x0b\n\x07KEY_ALT\x10\x02\x12\x11\
    \n\rKEY_BACKSPACE\x10\x03\x12\r\n\tKEY_BREAK\x10\x04\x12\r\n\tKEY_BEGIN\
    \x10\x05\x12\x0e\n\nKEY_CANCEL\x10\x06\x12\x11\n\rKEY_CAPS_LOCK\x10\x07\
    \x12\r\n\tKEY_CLEAR\x10\x08\x12\x0f\n\x0bKEY_COMMAND\x10\t\x12\x0f\n\x0b\
    KEY_CONTROL\x10\n\x12\x0f\n\x0bKEY_DECIMAL\x10\x0b\x12\x0e\n\nKEY_DELETE\
    \x10\x0c\x12\x0e\n\nKEY_DIVIDE\x10\r\x12\x12\n\x0eKEY_DOWN_ARROW\x10\x0e\
    \x12\x0b\n\x07KEY_END\x10\x0f\x12\x0e\n\nKEY_ESCAPE\x10\x10\x12\x0f\n\
    \x0bKEY_EXECUTE\x10\x11\x12\n\n\x06KEY_F1\x10\x12\x12\n\n\x06KEY_F2\x10\
    \x13\x12\n\n\x06KEY_F3\x10\x14\x12\n\n\x06KEY_F4\x10\x15\x12\n\n\x06KEY_\
    F5\x10\x16\x12\n\n\x06KEY_F6\x10\x17\x12\n\n\x06KEY_F7\x10\x18\x12\n\n\
    \x06KEY_F8\x10\x19\x12\n\n\x06KEY_F9\x10\x1a\x12\x0b\n\x07KEY_F10\x10\
    \x1b\x12\x0b\n\x07KEY_F11\x10\x1c\x12\x0b\n\x07KEY_F12\x10\x1d\x12\x0b\n\
    \x07KEY_F13\x10\x1e\x12\x0b\n\x07KEY_F14\x10\x1f\x12\x0b\n\x07KEY_F15\
    \x10\x20\x12\x0b\n\x07KEY_F16\x10!\x12\x0b\n\x07KEY_F17\x10\"\x12\x0b\n\
    \x07KEY_F18\x10#\x12\x0b\n\x07KEY_F19\x10$\x12\x0b\n\x07KEY_F20\x10%\x12\
    \x0b\n\x07KEY_F21\x10&\x12\x0b\n\x07KEY_F22\x10'\x12\x0b\n\x07KEY_F23\
    \x10(\x12\x0b\n\x07KEY_F24\x10)\x12\x0b\n\x07KEY_F25\x10*\x12\x0b\n\x07K\
    EY_F26\x10+\x12\x0b\n\x07KEY_F27\x10,\x12\x0b\n\x07KEY_F28\x10-\x12\x0b\
    \n\x07KEY_F29\x10.\x12\x0b\n\x07KEY_F30\x10/\x12\x0b\n\x07KEY_F31\x100\
    \x12\x0b\n\x07KEY_F32\x101\x12\x0b\n\x07KEY_F33\x102\x12\x0b\n\x07KEY_F3\
    4\x103\x12\x0b\n\x07KEY_F35\x104\x12\x0c\n\x08KEY_FIND\x105\x12\x0e\n\nK\
    EY_HANGUL\x106\x12\r\n\tKEY_HANJA\x107\x12\x0c\n\x08KEY_HELP\x108\x12\
    \x0c\n\x08KEY_HOME\x109\x12\x0e\n\nKEY_INSERT\x10:\x12\r\n\tKEY_KANJI\
    \x10;\x12\x11\n\rKEY_L_CONTROL\x10<\x12\x12\n\x0eKEY_LEFT_ARROW\x10=\x12\
    \x10\n\x0cKEY_LINEFEED\x10>\x12\x0e\n\nKEY_L_MENU\x10?\x12\x0f\n\x0bKEY_\
    L_SHIFT\x10@\x12\x18\n\x14KEY_MEDIA_NEXT_TRACK\x10A\x12\x18\n\x14KEY_MED\
    IA_PLAY_PAUSE\x10B\x12\x18\n\x14KEY_MEDIA_PREV_TRACK\x10C\x12\x12\n\x0eK\
    EY_MEDIA_STOP\x10D\x12\x0c\n\x08KEY_META\x10E\x12\x13\n\x0fKEY_MODE_CHAN\
    GE\x10F\x12\x10\n\x0cKEY_MULTIPLY\x10G\x12\x0f\n\x0bKEY_NUMLOCK\x10H\x12\
    \x0f\n\x0bKEY_NUMPAD0\x10I\x12\x0f\n\x0bKEY_NUMPAD1\x10J\x12\x0f\n\x0bKE\
    Y_NUMPAD2\x10K\x12\x0f\n\x0bKEY_NUMPAD3\x10L\x12\x0f\n\x0bKEY_NUMPAD4\
    \x10M\x12\x0f\n\x0bKEY_NUMPAD5\x10N\x12\x0f\n\x0bKEY_NUMPAD6\x10O\x12\
    \x0f\n\x0bKEY_NUMPAD7\x10P\x12\x0f\n\x0bKEY_NUMPAD8\x10Q\x12\x0f\n\x0bKE\
    Y_NUMPAD9\x10R\x12\x0e\n\nKEY_OPTION\x10S\x12\x11\n\rKEY_PAGE_DOWN\x10T\
    \x12\x0f\n\x0bKEY_PAGE_UP\x10U\x12\r\n\tKEY_PAUSE\x10V\x12\r\n\tKEY_PRIN\
    T\x10W\x12\x11\n\rKEY_PRINT_SCR\x10X\x12\x11\n\rKEY_R_CONTROL\x10Y\x12\
    \x0c\n\x08KEY_REDO\x10Z\x12\x0e\n\nKEY_RETURN\x10[\x12\x13\n\x0fKEY_RIGH\
    T_ARROW\x10\\\x12\x0f\n\x0bKEY_R_SHIFT\x10]\x12\x13\n\x0fKEY_SCROLL_LOCK\
    \x10^\x12\x0e\n\nKEY_SELECT\x10_\x12\x15\n\x11KEY_SCRIPT_SWITCH\x10`\x12\
    \r\n\tKEY_SHIFT\x10a\x12\x12\n\x0eKEY_SHIFT_LOCK\x10b\x12\r\n\tKEY_SPACE\
    \x10c\x12\x10\n\x0cKEY_SUBTRACT\x10d\x12\r\n\tKEY_SUPER\x10e\x12\x0f\n\
    \x0bKEY_SYS_REQ\x10f\x12\x0b\n\x07KEY_TAB\x10g\x12\x0c\n\x08KEY_UNDO\x10\
    h\x12\x10\n\x0cKEY_UP_ARROW\x10i\x12\x13\n\x0fKEY_VOLUME_DOWN\x10j\x12\
    \x13\n\x0fKEY_VOLUME_MUTE\x10k\x12\x11\n\rKEY_VOLUME_UP\x10l\x12\x10\n\
    \x0cKEY_MIC_MUTE\x10m\x12\x0f\n\x0bKEY_WINDOWS\x10n\x12\x0f\n\x0bKEY_UNI\
    CODE\x10o\x12\r\n\tKEY_OTHER\x10pb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(Key::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
