// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `server_config.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:DisplayImage)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DisplayImage {
    // message fields
    // @@protoc_insertion_point(field:DisplayImage.display_zone)
    pub display_zone: ::protobuf::EnumOrUnknown<super::display_zones::DisplayZone>,
    // @@protoc_insertion_point(field:DisplayImage.path)
    pub path: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:DisplayImage.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DisplayImage {
    fn default() -> &'a DisplayImage {
        <DisplayImage as ::protobuf::Message>::default_instance()
    }
}

impl DisplayImage {
    pub fn new() -> DisplayImage {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "display_zone",
            |m: &DisplayImage| { &m.display_zone },
            |m: &mut DisplayImage| { &mut m.display_zone },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "path",
            |m: &DisplayImage| { &m.path },
            |m: &mut DisplayImage| { &mut m.path },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DisplayImage>(
            "DisplayImage",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DisplayImage {
    const NAME: &'static str = "DisplayImage";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.display_zone = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.path = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.display_zone != ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.display_zone.value());
        }
        if !self.path.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.path);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.display_zone != ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.display_zone))?;
        }
        if !self.path.is_empty() {
            os.write_string(2, &self.path)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DisplayImage {
        DisplayImage::new()
    }

    fn clear(&mut self) {
        self.display_zone = ::protobuf::EnumOrUnknown::new(super::display_zones::DisplayZone::DISPLAY_ZONE_UNSPECIFIED);
        self.path.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DisplayImage {
        static instance: DisplayImage = DisplayImage {
            display_zone: ::protobuf::EnumOrUnknown::from_i32(0),
            path: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DisplayImage {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DisplayImage").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DisplayImage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DisplayImage {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:ServerConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ServerConfig {
    // message fields
    // @@protoc_insertion_point(field:ServerConfig.key_configs)
    pub key_configs: ::std::vec::Vec<super::key_config::KeyConfig>,
    // @@protoc_insertion_point(field:ServerConfig.display_images)
    pub display_images: ::std::vec::Vec<DisplayImage>,
    // @@protoc_insertion_point(field:ServerConfig.brightness)
    pub brightness: u32,
    // @@protoc_insertion_point(field:ServerConfig.boot_logo)
    pub boot_logo: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:ServerConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ServerConfig {
    fn default() -> &'a ServerConfig {
        <ServerConfig as ::protobuf::Message>::default_instance()
    }
}

impl ServerConfig {
    pub fn new() -> ServerConfig {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "key_configs",
            |m: &ServerConfig| { &m.key_configs },
            |m: &mut ServerConfig| { &mut m.key_configs },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "display_images",
            |m: &ServerConfig| { &m.display_images },
            |m: &mut ServerConfig| { &mut m.display_images },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "brightness",
            |m: &ServerConfig| { &m.brightness },
            |m: &mut ServerConfig| { &mut m.brightness },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "boot_logo",
            |m: &ServerConfig| { &m.boot_logo },
            |m: &mut ServerConfig| { &mut m.boot_logo },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ServerConfig>(
            "ServerConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ServerConfig {
    const NAME: &'static str = "ServerConfig";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.key_configs.push(is.read_message()?);
                },
                18 => {
                    self.display_images.push(is.read_message()?);
                },
                24 => {
                    self.brightness = is.read_uint32()?;
                },
                34 => {
                    self.boot_logo = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.key_configs {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.display_images {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.brightness != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.brightness);
        }
        if !self.boot_logo.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.boot_logo);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.key_configs {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        for v in &self.display_images {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.brightness != 0 {
            os.write_uint32(3, self.brightness)?;
        }
        if !self.boot_logo.is_empty() {
            os.write_string(4, &self.boot_logo)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ServerConfig {
        ServerConfig::new()
    }

    fn clear(&mut self) {
        self.key_configs.clear();
        self.display_images.clear();
        self.brightness = 0;
        self.boot_logo.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ServerConfig {
        static instance: ServerConfig = ServerConfig {
            key_configs: ::std::vec::Vec::new(),
            display_images: ::std::vec::Vec::new(),
            brightness: 0,
            boot_logo: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ServerConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ServerConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ServerConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13server_config.proto\x1a\x19commands/key_config.proto\x1a#commands/\
    common/display_zones.proto\"S\n\x0cDisplayImage\x12/\n\x0cdisplay_zone\
    \x18\x01\x20\x01(\x0e2\x0c.DisplayZoneR\x0bdisplayZone\x12\x12\n\x04path\
    \x18\x02\x20\x01(\tR\x04path\"\xb9\x01\n\x0cServerConfig\x126\n\x0bkey_c\
    onfigs\x18\x01\x20\x03(\x0b2\x15.key_config.KeyConfigR\nkeyConfigs\x124\
    \n\x0edisplay_images\x18\x02\x20\x03(\x0b2\r.DisplayImageR\rdisplayImage\
    s\x12\x1e\n\nbrightness\x18\x03\x20\x01(\rR\nbrightness\x12\x1b\n\tboot_\
    logo\x18\x04\x20\x01(\tR\x08bootLogob\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::key_config::file_descriptor().clone());
            deps.push(super::display_zones::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(DisplayImage::generated_message_descriptor_data());
            messages.push(ServerConfig::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
