// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `top_level.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:TopLevel)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TopLevel {
    // message oneof groups
    pub command: ::std::option::Option<top_level::Command>,
    // special fields
    // @@protoc_insertion_point(special_field:TopLevel.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TopLevel {
    fn default() -> &'a TopLevel {
        <TopLevel as ::protobuf::Message>::default_instance()
    }
}

impl TopLevel {
    pub fn new() -> TopLevel {
        ::std::default::Default::default()
    }

    // .key_config.KeyConfig key_config_command = 1;

    pub fn key_config_command(&self) -> &super::key_config::KeyConfig {
        match self.command {
            ::std::option::Option::Some(top_level::Command::KeyConfigCommand(ref v)) => v,
            _ => <super::key_config::KeyConfig as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_key_config_command(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_key_config_command(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(top_level::Command::KeyConfigCommand(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_key_config_command(&mut self, v: super::key_config::KeyConfig) {
        self.command = ::std::option::Option::Some(top_level::Command::KeyConfigCommand(v))
    }

    // Mutable pointer to the field.
    pub fn mut_key_config_command(&mut self) -> &mut super::key_config::KeyConfig {
        if let ::std::option::Option::Some(top_level::Command::KeyConfigCommand(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(top_level::Command::KeyConfigCommand(super::key_config::KeyConfig::new()));
        }
        match self.command {
            ::std::option::Option::Some(top_level::Command::KeyConfigCommand(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_key_config_command(&mut self) -> super::key_config::KeyConfig {
        if self.has_key_config_command() {
            match self.command.take() {
                ::std::option::Option::Some(top_level::Command::KeyConfigCommand(v)) => v,
                _ => panic!(),
            }
        } else {
            super::key_config::KeyConfig::new()
        }
    }

    // .display_zone_image.SetDisplayZoneImage set_display_zone_image_command = 2;

    pub fn set_display_zone_image_command(&self) -> &super::display_zone_image::SetDisplayZoneImage {
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetDisplayZoneImageCommand(ref v)) => v,
            _ => <super::display_zone_image::SetDisplayZoneImage as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_set_display_zone_image_command(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_set_display_zone_image_command(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetDisplayZoneImageCommand(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_display_zone_image_command(&mut self, v: super::display_zone_image::SetDisplayZoneImage) {
        self.command = ::std::option::Option::Some(top_level::Command::SetDisplayZoneImageCommand(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_display_zone_image_command(&mut self) -> &mut super::display_zone_image::SetDisplayZoneImage {
        if let ::std::option::Option::Some(top_level::Command::SetDisplayZoneImageCommand(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(top_level::Command::SetDisplayZoneImageCommand(super::display_zone_image::SetDisplayZoneImage::new()));
        }
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetDisplayZoneImageCommand(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_display_zone_image_command(&mut self) -> super::display_zone_image::SetDisplayZoneImage {
        if self.has_set_display_zone_image_command() {
            match self.command.take() {
                ::std::option::Option::Some(top_level::Command::SetDisplayZoneImageCommand(v)) => v,
                _ => panic!(),
            }
        } else {
            super::display_zone_image::SetDisplayZoneImage::new()
        }
    }

    // .display_zone_image.ClearDisplayZoneImage clear_display_zone_image_command = 3;

    pub fn clear_display_zone_image_command(&self) -> &super::display_zone_image::ClearDisplayZoneImage {
        match self.command {
            ::std::option::Option::Some(top_level::Command::ClearDisplayZoneImageCommand(ref v)) => v,
            _ => <super::display_zone_image::ClearDisplayZoneImage as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_clear_display_zone_image_command(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_clear_display_zone_image_command(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(top_level::Command::ClearDisplayZoneImageCommand(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_clear_display_zone_image_command(&mut self, v: super::display_zone_image::ClearDisplayZoneImage) {
        self.command = ::std::option::Option::Some(top_level::Command::ClearDisplayZoneImageCommand(v))
    }

    // Mutable pointer to the field.
    pub fn mut_clear_display_zone_image_command(&mut self) -> &mut super::display_zone_image::ClearDisplayZoneImage {
        if let ::std::option::Option::Some(top_level::Command::ClearDisplayZoneImageCommand(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(top_level::Command::ClearDisplayZoneImageCommand(super::display_zone_image::ClearDisplayZoneImage::new()));
        }
        match self.command {
            ::std::option::Option::Some(top_level::Command::ClearDisplayZoneImageCommand(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_clear_display_zone_image_command(&mut self) -> super::display_zone_image::ClearDisplayZoneImage {
        if self.has_clear_display_zone_image_command() {
            match self.command.take() {
                ::std::option::Option::Some(top_level::Command::ClearDisplayZoneImageCommand(v)) => v,
                _ => panic!(),
            }
        } else {
            super::display_zone_image::ClearDisplayZoneImage::new()
        }
    }

    // .display_zone_image.ClearAllDisplayZoneImages clear_all_display_zone_images_command = 4;

    pub fn clear_all_display_zone_images_command(&self) -> &super::display_zone_image::ClearAllDisplayZoneImages {
        match self.command {
            ::std::option::Option::Some(top_level::Command::ClearAllDisplayZoneImagesCommand(ref v)) => v,
            _ => <super::display_zone_image::ClearAllDisplayZoneImages as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_clear_all_display_zone_images_command(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_clear_all_display_zone_images_command(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(top_level::Command::ClearAllDisplayZoneImagesCommand(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_clear_all_display_zone_images_command(&mut self, v: super::display_zone_image::ClearAllDisplayZoneImages) {
        self.command = ::std::option::Option::Some(top_level::Command::ClearAllDisplayZoneImagesCommand(v))
    }

    // Mutable pointer to the field.
    pub fn mut_clear_all_display_zone_images_command(&mut self) -> &mut super::display_zone_image::ClearAllDisplayZoneImages {
        if let ::std::option::Option::Some(top_level::Command::ClearAllDisplayZoneImagesCommand(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(top_level::Command::ClearAllDisplayZoneImagesCommand(super::display_zone_image::ClearAllDisplayZoneImages::new()));
        }
        match self.command {
            ::std::option::Option::Some(top_level::Command::ClearAllDisplayZoneImagesCommand(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_clear_all_display_zone_images_command(&mut self) -> super::display_zone_image::ClearAllDisplayZoneImages {
        if self.has_clear_all_display_zone_images_command() {
            match self.command.take() {
                ::std::option::Option::Some(top_level::Command::ClearAllDisplayZoneImagesCommand(v)) => v,
                _ => panic!(),
            }
        } else {
            super::display_zone_image::ClearAllDisplayZoneImages::new()
        }
    }

    // .brightness.SetBrightness set_brightness_command = 5;

    pub fn set_brightness_command(&self) -> &super::brightness::SetBrightness {
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetBrightnessCommand(ref v)) => v,
            _ => <super::brightness::SetBrightness as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_set_brightness_command(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_set_brightness_command(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetBrightnessCommand(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_brightness_command(&mut self, v: super::brightness::SetBrightness) {
        self.command = ::std::option::Option::Some(top_level::Command::SetBrightnessCommand(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_brightness_command(&mut self) -> &mut super::brightness::SetBrightness {
        if let ::std::option::Option::Some(top_level::Command::SetBrightnessCommand(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(top_level::Command::SetBrightnessCommand(super::brightness::SetBrightness::new()));
        }
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetBrightnessCommand(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_brightness_command(&mut self) -> super::brightness::SetBrightness {
        if self.has_set_brightness_command() {
            match self.command.take() {
                ::std::option::Option::Some(top_level::Command::SetBrightnessCommand(v)) => v,
                _ => panic!(),
            }
        } else {
            super::brightness::SetBrightness::new()
        }
    }

    // .boot_logo.SetBootLogo set_boot_logo_command = 6;

    pub fn set_boot_logo_command(&self) -> &super::boot_logo::SetBootLogo {
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetBootLogoCommand(ref v)) => v,
            _ => <super::boot_logo::SetBootLogo as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_set_boot_logo_command(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_set_boot_logo_command(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetBootLogoCommand(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_boot_logo_command(&mut self, v: super::boot_logo::SetBootLogo) {
        self.command = ::std::option::Option::Some(top_level::Command::SetBootLogoCommand(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_boot_logo_command(&mut self) -> &mut super::boot_logo::SetBootLogo {
        if let ::std::option::Option::Some(top_level::Command::SetBootLogoCommand(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(top_level::Command::SetBootLogoCommand(super::boot_logo::SetBootLogo::new()));
        }
        match self.command {
            ::std::option::Option::Some(top_level::Command::SetBootLogoCommand(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_boot_logo_command(&mut self) -> super::boot_logo::SetBootLogo {
        if self.has_set_boot_logo_command() {
            match self.command.take() {
                ::std::option::Option::Some(top_level::Command::SetBootLogoCommand(v)) => v,
                _ => panic!(),
            }
        } else {
            super::boot_logo::SetBootLogo::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::key_config::KeyConfig>(
            "key_config_command",
            TopLevel::has_key_config_command,
            TopLevel::key_config_command,
            TopLevel::mut_key_config_command,
            TopLevel::set_key_config_command,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::display_zone_image::SetDisplayZoneImage>(
            "set_display_zone_image_command",
            TopLevel::has_set_display_zone_image_command,
            TopLevel::set_display_zone_image_command,
            TopLevel::mut_set_display_zone_image_command,
            TopLevel::set_set_display_zone_image_command,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::display_zone_image::ClearDisplayZoneImage>(
            "clear_display_zone_image_command",
            TopLevel::has_clear_display_zone_image_command,
            TopLevel::clear_display_zone_image_command,
            TopLevel::mut_clear_display_zone_image_command,
            TopLevel::set_clear_display_zone_image_command,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::display_zone_image::ClearAllDisplayZoneImages>(
            "clear_all_display_zone_images_command",
            TopLevel::has_clear_all_display_zone_images_command,
            TopLevel::clear_all_display_zone_images_command,
            TopLevel::mut_clear_all_display_zone_images_command,
            TopLevel::set_clear_all_display_zone_images_command,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::brightness::SetBrightness>(
            "set_brightness_command",
            TopLevel::has_set_brightness_command,
            TopLevel::set_brightness_command,
            TopLevel::mut_set_brightness_command,
            TopLevel::set_set_brightness_command,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::boot_logo::SetBootLogo>(
            "set_boot_logo_command",
            TopLevel::has_set_boot_logo_command,
            TopLevel::set_boot_logo_command,
            TopLevel::mut_set_boot_logo_command,
            TopLevel::set_set_boot_logo_command,
        ));
        oneofs.push(top_level::Command::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TopLevel>(
            "TopLevel",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TopLevel {
    const NAME: &'static str = "TopLevel";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.command = ::std::option::Option::Some(top_level::Command::KeyConfigCommand(is.read_message()?));
                },
                18 => {
                    self.command = ::std::option::Option::Some(top_level::Command::SetDisplayZoneImageCommand(is.read_message()?));
                },
                26 => {
                    self.command = ::std::option::Option::Some(top_level::Command::ClearDisplayZoneImageCommand(is.read_message()?));
                },
                34 => {
                    self.command = ::std::option::Option::Some(top_level::Command::ClearAllDisplayZoneImagesCommand(is.read_message()?));
                },
                42 => {
                    self.command = ::std::option::Option::Some(top_level::Command::SetBrightnessCommand(is.read_message()?));
                },
                50 => {
                    self.command = ::std::option::Option::Some(top_level::Command::SetBootLogoCommand(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.command {
            match v {
                &top_level::Command::KeyConfigCommand(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &top_level::Command::SetDisplayZoneImageCommand(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &top_level::Command::ClearDisplayZoneImageCommand(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &top_level::Command::ClearAllDisplayZoneImagesCommand(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &top_level::Command::SetBrightnessCommand(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &top_level::Command::SetBootLogoCommand(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.command {
            match v {
                &top_level::Command::KeyConfigCommand(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
                &top_level::Command::SetDisplayZoneImageCommand(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
                &top_level::Command::ClearDisplayZoneImageCommand(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
                &top_level::Command::ClearAllDisplayZoneImagesCommand(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
                },
                &top_level::Command::SetBrightnessCommand(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
                },
                &top_level::Command::SetBootLogoCommand(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TopLevel {
        TopLevel::new()
    }

    fn clear(&mut self) {
        self.command = ::std::option::Option::None;
        self.command = ::std::option::Option::None;
        self.command = ::std::option::Option::None;
        self.command = ::std::option::Option::None;
        self.command = ::std::option::Option::None;
        self.command = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TopLevel {
        static instance: TopLevel = TopLevel {
            command: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TopLevel {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TopLevel").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TopLevel {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TopLevel {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `TopLevel`
pub mod top_level {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:TopLevel.command)
    pub enum Command {
        // @@protoc_insertion_point(oneof_field:TopLevel.key_config_command)
        KeyConfigCommand(super::super::key_config::KeyConfig),
        // @@protoc_insertion_point(oneof_field:TopLevel.set_display_zone_image_command)
        SetDisplayZoneImageCommand(super::super::display_zone_image::SetDisplayZoneImage),
        // @@protoc_insertion_point(oneof_field:TopLevel.clear_display_zone_image_command)
        ClearDisplayZoneImageCommand(super::super::display_zone_image::ClearDisplayZoneImage),
        // @@protoc_insertion_point(oneof_field:TopLevel.clear_all_display_zone_images_command)
        ClearAllDisplayZoneImagesCommand(super::super::display_zone_image::ClearAllDisplayZoneImages),
        // @@protoc_insertion_point(oneof_field:TopLevel.set_brightness_command)
        SetBrightnessCommand(super::super::brightness::SetBrightness),
        // @@protoc_insertion_point(oneof_field:TopLevel.set_boot_logo_command)
        SetBootLogoCommand(super::super::boot_logo::SetBootLogo),
    }

    impl ::protobuf::Oneof for Command {
    }

    impl ::protobuf::OneofFull for Command {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::TopLevel as ::protobuf::MessageFull>::descriptor().oneof_by_name("command").unwrap()).clone()
        }
    }

    impl Command {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Command>("command")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0ftop_level.proto\x1a\x18commands/boot_logo.proto\x1a!commands/displ\
    ay_zone_image.proto\x1a\x19commands/brightness.proto\x1a\x19commands/key\
    _config.proto\"\xe3\x04\n\x08TopLevel\x12E\n\x12key_config_command\x18\
    \x01\x20\x01(\x0b2\x15.key_config.KeyConfigH\0R\x10keyConfigCommand\x12m\
    \n\x1eset_display_zone_image_command\x18\x02\x20\x01(\x0b2'.display_zone\
    _image.SetDisplayZoneImageH\0R\x1asetDisplayZoneImageCommand\x12s\n\x20c\
    lear_display_zone_image_command\x18\x03\x20\x01(\x0b2).display_zone_imag\
    e.ClearDisplayZoneImageH\0R\x1cclearDisplayZoneImageCommand\x12\x80\x01\
    \n%clear_all_display_zone_images_command\x18\x04\x20\x01(\x0b2-.display_\
    zone_image.ClearAllDisplayZoneImagesH\0R\x20clearAllDisplayZoneImagesCom\
    mand\x12Q\n\x16set_brightness_command\x18\x05\x20\x01(\x0b2\x19.brightne\
    ss.SetBrightnessH\0R\x14setBrightnessCommand\x12K\n\x15set_boot_logo_com\
    mand\x18\x06\x20\x01(\x0b2\x16.boot_logo.SetBootLogoH\0R\x12setBootLogoC\
    ommandB\t\n\x07commandb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(4);
            deps.push(super::boot_logo::file_descriptor().clone());
            deps.push(super::display_zone_image::file_descriptor().clone());
            deps.push(super::brightness::file_descriptor().clone());
            deps.push(super::key_config::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(TopLevel::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
