[package]
name = "config-frontend"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
iced = { features = ["tokio", "image"], git = "https://github.com/choden-dev/iced-with-radial-gradient", branch = "master" }
messaging = { path = "../messaging" }
protobuf = "3.7.2"
rfd = "0.15.4"

[lints]
workspace = true
